/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * NOTE: Do not edit this file to change website copy.
 * All editable text + content lives in `src/content.tsx`.
 * Edit that file and Vite will hot-reload the change.
 */

import React, { useState, useEffect, useMemo, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Search,
  Train,
  Bus,
  Car,
  Plane,
  Utensils,
  AlertCircle,
  ArrowRight,
  TrendingUp,
  Check,
  X
} from 'lucide-react';
import {
  SITE_TEXT,
  PERSONALITIES,
  INFO_CONTENT,
  ABOUT_PILLARS,
  DESTINATION_LIST,
  ALL_CITIES_LIST,
  getDestination,
  searchDestinations,
  destinationsForPersona,
  type Destination,
  type InfoTopic
} from './content';

const HOME_PAGE_SIZE = 15;

// --- View State ---
type View =
  | { kind: 'home' }
  | { kind: 'city'; cityId: string }
  | { kind: 'destinations' }
  | { kind: 'personas' }
  | { kind: 'about' }
  | { kind: 'search'; query: string }
  | { kind: 'info'; topic: InfoTopic };

const INFO_TOPICS: InfoTopic[] = [
  'how-it-works', 'mint-scoring', 'careers', 'travel-tribes',
  'ambassadors', 'support', 'privacy', 'terms', 'cookies'
];

// import.meta.env.BASE_URL always has a trailing slash; normalize to no trailing slash.
const BASE = import.meta.env.BASE_URL.replace(/\/$/, '');

function viewToUrl(v: View): string {
  const path = (() => {
    switch (v.kind) {
      case 'home':         return '/';
      case 'city':         return `/city/${encodeURIComponent(v.cityId)}`;
      case 'destinations': return '/destinations';
      case 'personas':     return '/personas';
      case 'about':        return '/about';
      case 'search':       return v.query ? `/search?q=${encodeURIComponent(v.query)}` : '/search';
      case 'info':         return `/info/${v.topic}`;
    }
  })();
  return BASE + path;
}

function urlToView(pathname: string, search: string): View {
  let p = pathname;
  if (BASE && p.startsWith(BASE)) p = p.slice(BASE.length);
  const segments = p.split('/').filter(Boolean);
  if (segments.length === 0) return { kind: 'home' };
  const [head, ...rest] = segments;
  if (head === 'city' && rest[0]) return { kind: 'city', cityId: decodeURIComponent(rest[0]) };
  if (head === 'destinations')    return { kind: 'destinations' };
  if (head === 'personas')        return { kind: 'personas' };
  if (head === 'about')           return { kind: 'about' };
  if (head === 'search') {
    const q = new URLSearchParams(search).get('q') ?? '';
    return { kind: 'search', query: q };
  }
  if (head === 'info' && rest[0] && (INFO_TOPICS as string[]).includes(rest[0])) {
    return { kind: 'info', topic: rest[0] as InfoTopic };
  }
  return { kind: 'home' };
}

export default function App() {
  const [view, setView] = useState<View>(() =>
    urlToView(window.location.pathname, window.location.search)
  );
  const [activePersonality, setActivePersonality] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');
  const [loginOpen, setLoginOpen] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const heroSearchRef = useRef<HTMLInputElement>(null);

  // Seed the initial history entry so a future popstate has a state to restore to.
  useEffect(() => {
    if (window.history.state == null) {
      window.history.replaceState(view, '', viewToUrl(view));
    }
    const onPop = (e: PopStateEvent) => {
      const next: View = e.state ?? urlToView(window.location.pathname, window.location.search);
      setView(next);
    };
    window.addEventListener('popstate', onPop);
    return () => window.removeEventListener('popstate', onPop);
  }, []);

  const navigate = (next: View) => {
    setView(next);
    const url = viewToUrl(next);
    if (url !== window.location.pathname + window.location.search) {
      window.history.pushState(next, '', url);
    }
  };

  const openCity = (cityId: string) => {
    if (!getDestination(cityId)) {
      const friendly = ALL_CITIES_LIST.find(c => c.id === cityId)?.name ?? cityId;
      showToast(SITE_TEXT.toasts.cityComingSoon(friendly));
      return;
    }
    navigate({ kind: 'city', cityId });
    window.scrollTo(0, 0);
  };

  const submitSearch = (q: string) => {
    const trimmed = q.trim();
    navigate({ kind: 'search', query: trimmed });
  };

  const focusHeroSearch = () => {
    if (view.kind !== 'home') {
      navigate({ kind: 'home' });
      setTimeout(() => heroSearchRef.current?.focus(), 350);
    } else {
      heroSearchRef.current?.focus();
      heroSearchRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  };

  const showToast = (message: string) => {
    setToast(message);
  };

  useEffect(() => {
    if (!toast) return;
    const t = setTimeout(() => setToast(null), 2800);
    return () => clearTimeout(t);
  }, [toast]);

  const selectedCity = view.kind === 'city' ? getDestination(view.cityId) : null;

  return (
    <div className="min-h-screen flex flex-col bg-surface-bg">
      {/* Navigation */}
      <nav className="w-full bg-slate-950 border-b border-slate-900 z-50">
        <div className="max-w-7xl mx-auto px-4 h-20 flex items-center justify-between">
          <div
            className="flex items-center gap-3 cursor-pointer group"
            onClick={() => navigate({ kind: 'home' })}
          >
            <div className="w-10 h-10 bg-brand rounded-xl flex items-center justify-center text-slate-950 font-black text-xl shadow-lg shadow-brand/20 group-hover:bg-white transition-all">{SITE_TEXT.brand.mark}</div>
            <span className="font-display text-2xl font-black text-white tracking-tighter">{SITE_TEXT.brand.name}<span className="text-brand">{SITE_TEXT.brand.nameAccent}</span></span>
          </div>
          <div className="hidden md:flex items-center gap-8 text-sm font-bold text-slate-400">
            <NavLink active={view.kind === 'destinations'} onClick={() => navigate({ kind: 'destinations' })}>{SITE_TEXT.nav.destinations}</NavLink>
            <NavLink active={view.kind === 'personas'}     onClick={() => navigate({ kind: 'personas' })}>{SITE_TEXT.nav.personaGuides}</NavLink>
            <NavLink active={view.kind === 'about'}        onClick={() => navigate({ kind: 'about' })}>{SITE_TEXT.nav.about}</NavLink>
            <button
              onClick={() => setLoginOpen(true)}
              className="bg-brand/10 text-brand px-6 py-2.5 rounded-xl border border-brand/20 hover:bg-brand hover:text-slate-950 transition-all font-black"
            >
              {SITE_TEXT.nav.login}
            </button>
          </div>
          <button
            className="md:hidden text-white"
            onClick={focusHeroSearch}
            aria-label="Search"
          >
            <Search size={24} />
          </button>
        </div>
      </nav>

      {/* Main Content */}
      <main className="flex-1">
        {view.kind === 'home' && (
          <HomeView
            onCityClick={openCity}
            activePersonality={activePersonality}
            setActivePersonality={setActivePersonality}
            searchQuery={searchQuery}
            setSearchQuery={setSearchQuery}
            onSubmitSearch={submitSearch}
            heroSearchRef={heroSearchRef}
          />
        )}
        {view.kind === 'city' && selectedCity && (
          <CityView
            city={selectedCity}
            activePersonality={activePersonality}
            setActivePersonality={setActivePersonality}
          />
        )}
        {view.kind === 'destinations' && (
          <DestinationsView onCityClick={openCity} />
        )}
        {view.kind === 'personas' && (
          <PersonaGuidesView onCityClick={openCity} />
        )}
        {view.kind === 'about' && (
          <AboutView onExploreClick={() => navigate({ kind: 'destinations' })} />
        )}
        {view.kind === 'search' && (
          <SearchView
            initialQuery={view.query}
            onCityClick={openCity}
            onSubmitSearch={submitSearch}
          />
        )}
        {view.kind === 'info' && (
          <InfoPageView
            topic={view.topic}
            onHome={() => navigate({ kind: 'home' })}
          />
        )}
      </main>

      {/* Footer */}
      <footer className="bg-slate-950 text-slate-400 pt-20 pb-10 border-t border-slate-900">
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-16">
            <div className="space-y-6">
              <div
                className="flex items-center gap-2 cursor-pointer"
                onClick={() => navigate({ kind: 'home' })}
              >
                <div className="w-8 h-8 bg-brand rounded-lg flex items-center justify-center text-slate-950 font-black text-sm">{SITE_TEXT.brand.mark}</div>
                <span className="font-display text-xl font-bold text-white tracking-tight">{SITE_TEXT.brand.name}{SITE_TEXT.brand.nameAccent}</span>
              </div>
              <p className="text-sm leading-relaxed opacity-60">{SITE_TEXT.footer.brandBlurb}</p>
            </div>

            <div>
              <h4 className="text-white font-bold mb-6 text-sm uppercase tracking-widest">{SITE_TEXT.footer.platformHeading}</h4>
              <ul className="space-y-4 text-xs font-bold">
                {SITE_TEXT.footer.platformLinks.map(link => (
                  <li key={link.label}>
                    <FooterLink onClick={() => navigate(link.view === 'info' ? { kind: 'info', topic: link.topic } : { kind: link.view })}>
                      {link.label}
                    </FooterLink>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h4 className="text-white font-bold mb-6 text-sm uppercase tracking-widest">{SITE_TEXT.footer.communityHeading}</h4>
              <ul className="space-y-4 text-xs font-bold">
                {SITE_TEXT.footer.communityLinks.map(link => (
                  <li key={link.label}>
                    <FooterLink onClick={() => navigate(link.view === 'info' ? { kind: 'info', topic: link.topic } : { kind: link.view })}>
                      {link.label}
                    </FooterLink>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h4 className="text-white font-bold mb-6 text-sm uppercase tracking-widest text-brand">{SITE_TEXT.footer.newsletterHeading}</h4>
              <p className="text-xs mb-4 opacity-60">{SITE_TEXT.footer.newsletterBlurb}</p>
              <NewsletterForm onSubscribed={(email) => showToast(SITE_TEXT.toasts.subscribed(email))} onInvalid={() => showToast(SITE_TEXT.toasts.invalidEmail)} />
            </div>
          </div>

          <div className="pt-8 border-t border-slate-900 flex flex-col md:flex-row items-center justify-between gap-4 text-[10px] font-bold uppercase tracking-widest">
            <p>{SITE_TEXT.footer.copyright}</p>
            <div className="flex gap-6">
              {SITE_TEXT.footer.legalLinks.map(link => (
                <React.Fragment key={link.label}>
                  <FooterLink onClick={() => navigate({ kind: 'info', topic: link.topic })}>
                    {link.label}
                  </FooterLink>
                </React.Fragment>
              ))}
            </div>
          </div>
        </div>
      </footer>

      {/* Login Modal */}
      <AnimatePresence>
        {loginOpen && (
          <LoginModal
            onClose={() => setLoginOpen(false)}
            onSuccess={(email) => {
              setLoginOpen(false);
              showToast(SITE_TEXT.toasts.loginWelcome(email.split('@')[0]));
            }}
          />
        )}
      </AnimatePresence>

      {/* Toast */}
      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ y: 60, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 60, opacity: 0 }}
            className="fixed bottom-8 left-1/2 -translate-x-1/2 z-[60] bg-slate-950 text-white px-6 py-4 rounded-2xl shadow-2xl shadow-slate-950/40 border border-slate-800 flex items-center gap-3"
          >
            <Check size={16} className="text-brand" strokeWidth={3} />
            <span className="text-xs font-bold uppercase tracking-widest">{toast}</span>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// --- Reusable link components ---

function NavLink({ children, onClick, active }: { children: React.ReactNode; onClick: () => void; active?: boolean }) {
  return (
    <a
      href="#"
      onClick={(e) => { e.preventDefault(); onClick(); }}
      className={`hover:text-brand transition-colors ${active ? 'text-brand' : ''}`}
    >
      {children}
    </a>
  );
}

function FooterLink({ children, onClick }: { children: React.ReactNode; onClick: () => void }) {
  return (
    <a
      href="#"
      onClick={(e) => { e.preventDefault(); onClick(); }}
      className="hover:text-brand"
    >
      {children}
    </a>
  );
}

function NewsletterForm({ onSubscribed, onInvalid }: { onSubscribed: (email: string) => void; onInvalid: () => void }) {
  const [email, setEmail] = useState('');
  const submit = () => {
    const e = email.trim();
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)) {
      onInvalid();
      return;
    }
    onSubscribed(e);
    setEmail('');
  };
  return (
    <div className="flex gap-2">
      <input
        type="email"
        placeholder={SITE_TEXT.footer.newsletterPlaceholder}
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        onKeyDown={(e) => { if (e.key === 'Enter') submit(); }}
        className="bg-slate-900 border border-slate-800 rounded-lg px-4 py-2 text-xs focus:outline-none focus:border-brand w-full"
      />
      <button
        onClick={submit}
        className="bg-brand text-slate-950 px-4 py-2 rounded-lg text-xs font-bold"
      >
        {SITE_TEXT.footer.newsletterButton}
      </button>
    </div>
  );
}

function LoginModal({ onClose, onSuccess }: { onClose: () => void; onSuccess: (email: string) => void }) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim() || !password.trim()) return;
    onSuccess(email.trim());
  };
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[70] bg-slate-950/70 backdrop-blur-md flex items-center justify-center p-4"
      onClick={onClose}
    >
      <motion.form
        initial={{ y: 30, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        exit={{ y: 30, opacity: 0 }}
        onClick={(e) => e.stopPropagation()}
        onSubmit={submit}
        className="bg-slate-950 border border-slate-800 rounded-[2rem] p-10 w-full max-w-md shadow-2xl"
      >
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-brand rounded-xl flex items-center justify-center text-slate-950 font-black text-xl">{SITE_TEXT.brand.mark}</div>
            <span className="font-display text-xl font-black text-white tracking-tighter">{SITE_TEXT.loginModal.title}</span>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-slate-500 hover:text-white transition-colors"
            aria-label="Close login"
          >
            <X size={20} />
          </button>
        </div>
        <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-slate-500 mb-6">{SITE_TEXT.loginModal.meta}</p>
        <label className="block text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">{SITE_TEXT.loginModal.emailLabel}</label>
        <input
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder={SITE_TEXT.loginModal.emailPlaceholder}
          className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand mb-4"
          autoFocus
        />
        <label className="block text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">{SITE_TEXT.loginModal.passwordLabel}</label>
        <input
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          placeholder={SITE_TEXT.loginModal.passwordPlaceholder}
          className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand mb-8"
        />
        <button
          type="submit"
          className="w-full bg-brand text-slate-950 font-black uppercase tracking-widest text-xs py-4 rounded-xl hover:bg-white transition-colors"
        >
          {SITE_TEXT.loginModal.submitButton}
        </button>
        <p className="text-[10px] text-slate-500 mt-6 text-center">{SITE_TEXT.loginModal.fineprint}</p>
      </motion.form>
    </motion.div>
  );
}

// --- Views ---

function HomeView({
  onCityClick,
  activePersonality,
  setActivePersonality,
  searchQuery,
  setSearchQuery,
  onSubmitSearch,
  heroSearchRef
}: {
  onCityClick: (id: string) => void;
  activePersonality: string;
  setActivePersonality: (p: string) => void;
  searchQuery: string;
  setSearchQuery: (q: string) => void;
  onSubmitSearch: (q: string) => void;
  heroSearchRef: React.RefObject<HTMLInputElement | null>;
}) {
  const filteredCities = useMemo(
    () => activePersonality === 'All' ? ALL_CITIES_LIST : destinationsForPersona(activePersonality),
    [activePersonality]
  );

  const [page, setPage] = useState(1);
  useEffect(() => { setPage(1); }, [activePersonality]);
  const pageCount = Math.max(1, Math.ceil(filteredCities.length / HOME_PAGE_SIZE));
  const safePage = Math.min(page, pageCount);
  const visibleCities = filteredCities.slice((safePage - 1) * HOME_PAGE_SIZE, safePage * HOME_PAGE_SIZE);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="pb-20"
    >
      <section className="relative h-[450px] flex items-center justify-center text-center overflow-hidden">
        <div className="absolute inset-0 z-0">
          <img
            src="https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=2076&auto=format&fit=crop"
            className="w-full h-full object-cover brightness-[0.3]"
            alt="Hero Background"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-slate-950/20 to-slate-950/40"></div>
        </div>
        <div className="relative z-10 max-w-4xl px-4">
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-brand/10 border border-brand/20 text-brand text-[10px] font-black uppercase tracking-[0.3em] px-4 py-2 rounded-full w-fit mx-auto mb-8 backdrop-blur-md"
          >
            {SITE_TEXT.hero.eyebrow}
          </motion.div>
          <motion.h1
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="text-5xl md:text-7xl text-white mb-8 font-black tracking-tighter uppercase"
          >
            {SITE_TEXT.hero.titleLine1} <span className="text-brand">{SITE_TEXT.hero.titleAccent}</span><br />
            {SITE_TEXT.hero.titleLine2} <span className="italic">{SITE_TEXT.hero.titleItalic}</span>
          </motion.h1>
          <div className="relative max-w-xl mx-auto group">
            <input
              ref={heroSearchRef}
              type="text"
              placeholder={SITE_TEXT.hero.searchPlaceholder}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') onSubmitSearch(searchQuery); }}
              className="w-full h-16 bg-white/10 backdrop-blur-xl border border-white/10 rounded-2xl pl-16 pr-6 text-white placeholder:text-white/40 focus:outline-none focus:ring-4 focus:ring-brand/30 transition-all shadow-2xl group-hover:bg-white/20"
            />
            <button
              type="button"
              onClick={() => onSubmitSearch(searchQuery)}
              className="absolute left-6 top-1/2 -translate-y-1/2 text-white/50 hover:text-brand transition-colors"
              aria-label="Submit search"
            >
              <Search size={24} />
            </button>
          </div>
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-4 mt-[-40px] relative z-20">
        <div className="bg-white rounded-[2.5rem] p-4 shadow-xl shadow-slate-200/40 mb-12 flex items-center gap-2 overflow-x-auto no-scrollbar border border-slate-100/50">
          <span className="text-[10px] font-black uppercase text-slate-400 px-6 shrink-0 border-r border-slate-100 py-2 hidden md:block">Personality</span>
          <div className="flex gap-2 p-1">
            {PERSONALITIES.map(p => (
              <button
                key={p.id}
                onClick={() => setActivePersonality(p.id)}
                className={`flex items-center gap-2 px-6 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap ${
                  activePersonality === p.id
                    ? 'bg-slate-900 text-white shadow-lg shadow-slate-900/20'
                    : 'bg-slate-50 text-slate-500 hover:bg-slate-100'
                }`}
              >
                {p.icon}
                {p.id}
              </button>
            ))}
          </div>
        </div>

        <div className="city-grid">
          {visibleCities.map(c => (
            <CityCard
              key={c.id}
              title={c.name}
              tagline={c.tagline}
              image={c.image}
              rating={c.rating}
              onClick={() => onCityClick(c.id)}
            />
          ))}
        </div>
        {filteredCities.length === 0 && (
          <div className="text-center py-20 text-slate-400 text-sm font-bold uppercase tracking-widest">
            {SITE_TEXT.emptyStates.homePersonaNoMatch}
          </div>
        )}

        {pageCount > 1 && (
          <Pagination page={safePage} pageCount={pageCount} onChange={setPage} />
        )}
      </section>
    </motion.div>
  );
}

function Pagination({ page, pageCount, onChange }: { page: number; pageCount: number; onChange: (p: number) => void }) {
  const prevDisabled = page <= 1;
  const nextDisabled = page >= pageCount;
  const btn = "px-5 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest border transition-all";
  return (
    <div className="flex items-center justify-center gap-4 mt-12">
      <button
        type="button"
        onClick={() => onChange(page - 1)}
        disabled={prevDisabled}
        className={`${btn} ${prevDisabled ? 'border-slate-100 text-slate-300 cursor-not-allowed' : 'border-slate-200 text-slate-700 hover:border-brand hover:text-brand'}`}
      >
        Prev
      </button>
      <span className="text-[10px] font-black uppercase tracking-widest text-slate-500">
        Page {page} of {pageCount}
      </span>
      <button
        type="button"
        onClick={() => onChange(page + 1)}
        disabled={nextDisabled}
        className={`${btn} ${nextDisabled ? 'border-slate-100 text-slate-300 cursor-not-allowed' : 'border-slate-200 text-slate-700 hover:border-brand hover:text-brand'}`}
      >
        Next
      </button>
    </div>
  );
}

function CityView({ city, activePersonality, setActivePersonality }: { city: Destination, activePersonality: string, setActivePersonality: (p: string) => void }) {
  const combinedEffort = (city.matrix.money + city.matrix.fatigue) / 2;
  const t = SITE_TEXT.cityDetail;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="max-w-[1440px] mx-auto px-4 py-8"
    >
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Column */}
        <div className="lg:col-span-4 order-1 lg:order-1 space-y-8">
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="relative group rounded-[3rem] overflow-hidden aspect-[4/5] lg:aspect-[1/1] shadow-2xl shadow-slate-300"
          >
            <img src={city.heroImage} className="absolute inset-0 w-full h-full object-cover transition-transform duration-700" alt={city.name} />
            <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-900/40 to-transparent"></div>
            <div className="absolute inset-0 p-8 flex flex-col justify-end">
              <div className="text-white/5 text-[10rem] font-black tracking-tighter absolute top-0 right-0 pointer-events-none select-none uppercase -mt-20 -mr-10">{city.name.toUpperCase()}</div>
              <div className="bg-orange-400 text-slate-950 text-[10px] font-black uppercase tracking-[0.2em] px-4 py-1.5 rounded-full w-fit mb-6 shadow-lg">{t.verifiedBadge}</div>
              <h1 className="text-5xl lg:text-7xl text-white font-black mb-4 leading-tight tracking-tight uppercase">{t.oneDayInPrefix}<br/>{t.oneDayInLink} {city.name}</h1>
              <div className="bg-brand text-slate-950 text-xs font-bold px-6 py-3 rounded-2xl flex items-center gap-3 w-fit shadow-xl uppercase tracking-widest">
                <Check size={18} className="text-slate-950" strokeWidth={3} />
                {city.verdict}
              </div>
            </div>
          </motion.div>

          <div className="bg-white rounded-[2.5rem] p-8 shadow-sm border border-slate-100">
            <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-400 mb-8 border-b border-slate-50 pb-4">{t.gettingThere}</h4>
            <div className="space-y-4">
              {city.reach.map((r, i) => (
                <div key={i} className="flex items-center gap-6 group hover:translate-x-2 transition-transform">
                  <div className="w-12 h-12 rounded-2xl bg-slate-50 flex items-center justify-center text-slate-400 group-hover:bg-brand group-hover:text-slate-950 transition-all shadow-sm">
                    {r.type === 'Train' ? <Train size={20} /> : r.type === 'Road' ? <Car size={20} /> : r.type === 'Flight' ? <Plane size={20} /> : <Bus size={20} />}
                  </div>
                  <div className="flex-1">
                    <div className="flex justify-between items-center">
                      <h5 className="text-[13px] font-black text-slate-800">{r.detail}</h5>
                      <span className="text-[10px] font-black text-brand">{r.cost}</span>
                    </div>
                    <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mt-0.5">{r.time} • {r.hub}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-emerald-50/20 rounded-[2.5rem] p-8 border border-emerald-100">
            <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-emerald-600 mb-6 flex items-center gap-3">
              <AlertCircle size={16} />
              {t.survivalHeading}
            </h4>
            <div className="space-y-4">
              {city.tips.slice(0, 3).map((tip, i) => (
                <div key={i} className="flex gap-4 items-start">
                  <div className="w-2 h-2 bg-emerald-400 rounded-full mt-1.5 shrink-0"></div>
                  <p className="text-[13px] font-bold text-emerald-950 leading-relaxed italic opacity-80">{tip}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Middle Column */}
        <div className="lg:col-span-5 order-2 lg:order-2 bg-white rounded-[3.5rem] shadow-xl shadow-slate-200/40 border border-slate-100 overflow-hidden relative min-h-[800px]">
          <div className="p-10 border-b border-slate-50 flex items-center justify-between sticky top-0 bg-white/90 backdrop-blur-md z-40">
            <div>
              <h3 className="text-xl font-black tracking-[0.2em] text-slate-900 uppercase">{t.timelineTitle}</h3>
              <p className="text-brand text-[10px] font-black mt-1 uppercase tracking-widest">{t.timelineSub}</p>
            </div>
            <div className="flex gap-2">
              {t.quickFilters.map(tag => (
                <button key={tag} onClick={() => setActivePersonality(tag)} className={`px-4 py-2 text-[9px] font-black border border-slate-100 rounded-xl transition-all uppercase tracking-widest ${activePersonality === tag ? 'bg-slate-900 text-white border-slate-900' : 'bg-slate-50 text-slate-400 hover:text-brand'}`}>{tag}</button>
              ))}
            </div>
          </div>

          <div className="p-10 space-y-12 relative">
            <div className="absolute left-[59px] top-12 bottom-12 w-[1px] bg-slate-100"></div>
            <AnimatePresence mode="popLayout">
              {city.itinerary.map((item, i) => {
                const isMatch = activePersonality === 'All' || item.personalities.includes(activePersonality);
                return (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{
                      opacity: isMatch ? 1 : 0.1,
                      filter: isMatch ? 'blur(0px)' : 'blur(1px)'
                    }}
                    className="relative pl-16 flex flex-col"
                  >
                    <div className="absolute left-[-2px] top-0 w-12 h-12 bg-white flex items-center justify-center z-10">
                      <div className={`itinerary-dot ${isMatch ? 'bg-brand' : 'bg-slate-100 shadow-none grayscale'}`}></div>
                    </div>
                    <div className="mb-2">
                      <div className="flex items-center gap-4 text-[10px] font-black tracking-widest text-slate-400">
                        <span className={isMatch ? 'text-brand' : ''}>{item.time}</span>
                        <span className="w-6 h-[0.5px] bg-slate-100"></span>
                        <span>{item.duration}</span>
                      </div>
                    </div>
                    <h4 className={`text-xl font-black tracking-tight mb-2 ${isMatch ? 'text-slate-900' : 'text-slate-300'}`}>{item.place}</h4>
                    <p className={`text-[13px] font-medium leading-relaxed max-w-sm mb-4 ${isMatch ? 'text-slate-500' : 'text-slate-200'}`}>
                      {item.description}
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {item.personalities.map(p => (
                        <span key={p} className={`text-[9px] font-black uppercase px-2 py-0.5 rounded-lg border transition-all ${isMatch && p === activePersonality ? 'bg-brand text-slate-950 border-brand' : 'bg-slate-50 text-slate-300 border-slate-100'}`}>{p}</span>
                      ))}
                    </div>
                  </motion.div>
                );
              })}
            </AnimatePresence>
          </div>
        </div>

        {/* Right Column */}
        <div className="lg:col-span-3 order-3 space-y-8">
          <div className="bg-white rounded-[2.5rem] p-10 shadow-sm border border-slate-100 text-center">
            <h4 className="text-[10px] font-black uppercase tracking-[0.4em] text-slate-400 mb-8">{t.mintScoreTitle}</h4>

            <div className="relative w-full max-w-[220px] mx-auto">
              <svg className="w-full h-auto block gauge-svg" viewBox="0 0 100 60">
                <path d="M10,50 A40,40 0 0,1 90,50" fill="none" stroke="#F1F5F9" strokeWidth="10" strokeLinecap="round" />
                <path d="M10,50 A40,40 0 0,1 90,50" fill="none" stroke="#00B894" strokeWidth="10" strokeLinecap="round" strokeDasharray="125.6" strokeDashoffset={125.6 * (city.rating / 10 - 1)} />
                <motion.line
                  initial={{ rotate: -90 }}
                  animate={{ rotate: -90 + (city.rating / 10 * 180) }}
                  transition={{ duration: 1.5, type: 'spring' }}
                  x1="50" y1="50" x2="50" y2="15"
                  stroke="#0F172A" strokeWidth="3" strokeLinecap="round"
                  style={{ originX: '50px', originY: '50px' }}
                />
                <circle cx="50" cy="50" r="5" fill="#0F172A" />
              </svg>
              <div className="text-4xl font-black text-slate-950 tracking-tighter -mt-4">
                {Math.round(city.rating * 10)}
              </div>
            </div>
            <p className="text-[9px] font-black uppercase tracking-widest text-slate-400 mt-4 leading-tight">{t.mintScoreFooter}</p>
          </div>

          <div className="bg-slate-950 rounded-[3rem] p-10 shadow-2xl shadow-slate-950/40 text-white overflow-hidden">
            <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-white/30 mb-8">{t.matrixTitle}</h4>
            <div className="space-y-10">
              <MatrixVisual label={t.effortLabel} value={combinedEffort} level={combinedEffort > 70 ? t.effortLevelHigh : t.effortLevelMid} color="bg-orange-500" />
              <MatrixVisual label={t.payoffLabel} value={city.matrix.payoff} level={t.payoffLevel} color="bg-indigo-500" />
            </div>
          </div>

          <div className="bg-white rounded-[2.5rem] shadow-sm border border-slate-100 overflow-hidden flex">
            <div className="flex-1 glass-green p-8 border-r border-slate-50">
              <span className="text-[8px] font-black uppercase tracking-widest text-emerald-600 bg-white/80 px-2 py-0.5 rounded-md border border-emerald-500/10 mb-6 inline-block">{t.prosLabel}</span>
              <div className="space-y-5 mt-4">
                {city.pros.map(p => (
                  <div key={p} className="flex gap-3 text-[10px] font-bold text-slate-800 leading-tight">
                    <Check size={12} className="text-emerald-500 shrink-0 mt-0.5" strokeWidth={3} />
                    {p}
                  </div>
                ))}
              </div>
            </div>
            <div className="flex-1 glass-red p-8">
              <span className="text-[8px] font-black uppercase tracking-widest text-rose-600 bg-white/80 px-2 py-0.5 rounded-md border border-rose-500/10 mb-6 inline-block">{t.consLabel}</span>
              <div className="space-y-5 mt-4">
                {city.cons.map(c => (
                  <div key={c} className="flex gap-3 text-[10px] font-bold text-slate-800 leading-tight">
                    <X size={12} className="text-rose-500 shrink-0 mt-0.5" strokeWidth={3} />
                    {c}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="mt-16 bg-white rounded-[2.5rem] p-6 shadow-xl shadow-slate-200/30 border border-slate-100 flex flex-col lg:flex-row items-center justify-between gap-8 max-w-6xl mx-auto">
        <div className="flex items-center gap-6 px-4">
          <div className="w-12 h-12 bg-slate-950 rounded-2xl flex items-center justify-center text-brand">
            <Utensils size={20} />
          </div>
          <div>
            <h4 className="text-lg font-black tracking-tight uppercase">{t.budgetTitle}</h4>
            <p className="text-[9px] text-slate-400 font-bold uppercase tracking-[0.2em]">{t.budgetSubPrefix}{city.name}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex flex-col items-center">
            <span className="text-[8px] font-black text-slate-400 uppercase tracking-widest mb-1 opacity-50">{t.backpacker}</span>
            <div className="bg-slate-50 border border-slate-100 px-6 py-2.5 rounded-xl text-xs font-black text-slate-900">{city.budget.backpacker}</div>
          </div>
          <div className="flex flex-col items-center -mt-2">
            <span className="text-[8px] font-black text-brand uppercase tracking-widest mb-1">{t.optimum}</span>
            <div className="bg-brand border border-brand/20 px-8 py-4 rounded-2xl text-base font-black text-slate-950 shadow-xl shadow-brand/20">{city.budget.recommended}</div>
          </div>
          <div className="flex flex-col items-center">
            <span className="text-[8px] font-black text-slate-400 uppercase tracking-widest mb-1 opacity-50">{t.luxury}</span>
            <div className="bg-slate-50 border border-slate-100 px-6 py-2.5 rounded-xl text-xs font-black text-slate-900">{city.budget.luxury}</div>
          </div>
        </div>
      </div>

      {/* Must-Try Foods */}
      {city.mustTry.length > 0 && (
        <div className="mt-12 max-w-6xl mx-auto">
          <h3 className="text-2xl font-black uppercase tracking-tight text-slate-900 mb-6 px-4">{t.mustTryTitle}</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 px-4">
            {city.mustTry.map(item => (
              <div key={item.name} className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-sm flex gap-5 items-start">
                <div className="w-12 h-12 bg-brand/10 text-brand rounded-2xl flex items-center justify-center shrink-0">
                  <Utensils size={20} />
                </div>
                <div>
                  <h4 className="text-base font-black uppercase tracking-tight text-slate-900 mb-2">{item.name}</h4>
                  <p className="text-[13px] text-slate-500 leading-relaxed">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </motion.div>
  );
}

// --- New Views ---

function PageHeader({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle?: string }) {
  return (
    <div className="max-w-7xl mx-auto px-4 pt-16 pb-10 text-center">
      <div className="bg-brand/10 border border-brand/20 text-brand text-[10px] font-black uppercase tracking-[0.3em] px-4 py-2 rounded-full w-fit mx-auto mb-6">
        {eyebrow}
      </div>
      <h1 className="text-4xl md:text-6xl font-black tracking-tighter uppercase text-slate-950 mb-4">{title}</h1>
      {subtitle && <p className="text-slate-500 text-base max-w-2xl mx-auto leading-relaxed">{subtitle}</p>}
    </div>
  );
}

function DestinationsView({ onCityClick }: { onCityClick: (id: string) => void }) {
  const t = SITE_TEXT.destinationsPage;
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader
        eyebrow={t.eyebrow}
        title={t.title}
        subtitle={t.subtitle(DESTINATION_LIST.length)}
      />
      <section className="max-w-7xl mx-auto px-4">
        <div className="city-grid">
          {DESTINATION_LIST.map(c => (
            <CityCard
              key={c.id}
              title={c.name}
              tagline={c.tagline}
              image={c.image}
              rating={c.rating}
              onClick={() => onCityClick(c.id)}
            />
          ))}
        </div>
      </section>
    </motion.div>
  );
}

function PersonaGuidesView({ onCityClick }: { onCityClick: (id: string) => void }) {
  const [selected, setSelected] = useState<string>('All');
  const matches = useMemo(() => destinationsForPersona(selected), [selected]);
  const t = SITE_TEXT.personasPage;

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader
        eyebrow={t.eyebrow}
        title={t.title}
        subtitle={t.subtitle}
      />
      <section className="max-w-7xl mx-auto px-4">
        <div className="bg-white rounded-[2.5rem] p-4 shadow-xl shadow-slate-200/40 mb-12 flex items-center gap-2 overflow-x-auto no-scrollbar border border-slate-100/50">
          <span className="text-[10px] font-black uppercase text-slate-400 px-6 shrink-0 border-r border-slate-100 py-2 hidden md:block">{t.pickOneLabel}</span>
          <div className="flex gap-2 p-1">
            {PERSONALITIES.map(p => (
              <button
                key={p.id}
                onClick={() => setSelected(p.id)}
                className={`flex items-center gap-2 px-6 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap ${
                  selected === p.id
                    ? 'bg-slate-900 text-white shadow-lg shadow-slate-900/20'
                    : 'bg-slate-50 text-slate-500 hover:bg-slate-100'
                }`}
              >
                {p.icon}
                {p.id}
              </button>
            ))}
          </div>
        </div>
        <div className="city-grid">
          {matches.map(c => (
            <CityCard
              key={c.id}
              title={c.name}
              tagline={c.tagline}
              image={c.image}
              rating={c.rating}
              onClick={() => onCityClick(c.id)}
            />
          ))}
        </div>
        {matches.length === 0 && (
          <div className="text-center py-20 text-slate-400 text-sm font-bold uppercase tracking-widest">
            {SITE_TEXT.emptyStates.personaPageNoMatch(selected)}
          </div>
        )}
      </section>
    </motion.div>
  );
}

function AboutView({ onExploreClick }: { onExploreClick: () => void }) {
  const t = SITE_TEXT.aboutPage;
  const stats = t.stats.map(s =>
    s.value === 'auto-cities-count' ? { ...s, value: DESTINATION_LIST.length.toString() } : s
  );

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader
        eyebrow={t.eyebrow}
        title={t.title}
        subtitle={t.subtitle}
      />
      <section className="max-w-5xl mx-auto px-4">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-16">
          {stats.map(s => (
            <div key={s.label} className="bg-white rounded-[2rem] p-6 border border-slate-100 shadow-sm text-center">
              <div className="text-3xl font-black text-slate-950 tracking-tighter mb-2">{s.value}</div>
              <div className="text-[9px] font-black uppercase tracking-widest text-slate-400">{s.label}</div>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
          {ABOUT_PILLARS.map(p => (
            <div key={p.title} className="bg-white rounded-[2.5rem] p-8 border border-slate-100 shadow-sm">
              <div className="w-12 h-12 bg-brand/10 text-brand rounded-2xl flex items-center justify-center mb-6">
                {p.icon}
              </div>
              <h3 className="text-lg font-black uppercase tracking-tight text-slate-900 mb-3">{p.title}</h3>
              <p className="text-[13px] text-slate-500 leading-relaxed">{p.body}</p>
            </div>
          ))}
        </div>

        <div className="bg-slate-950 rounded-[3rem] p-12 text-white text-center">
          <h2 className="text-3xl md:text-4xl font-black tracking-tighter uppercase mb-4">{t.ctaTitle}</h2>
          <p className="text-slate-400 max-w-xl mx-auto mb-8 leading-relaxed">{t.ctaBody}</p>
          <button
            onClick={onExploreClick}
            className="bg-brand text-slate-950 px-8 py-4 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-white transition-colors"
          >
            {t.ctaButton}
          </button>
        </div>
      </section>
    </motion.div>
  );
}

function SearchView({ initialQuery, onCityClick, onSubmitSearch }: { initialQuery: string; onCityClick: (id: string) => void; onSubmitSearch: (q: string) => void }) {
  const [query, setQuery] = useState(initialQuery);
  useEffect(() => { setQuery(initialQuery); }, [initialQuery]);
  const t = SITE_TEXT.searchPage;

  const results = useMemo(() => searchDestinations(query), [query]);

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader
        eyebrow={t.eyebrow}
        title={query ? `"${query}"` : t.fallbackTitle}
        subtitle={t.summary(results.length)}
      />
      <section className="max-w-7xl mx-auto px-4">
        <div className="relative max-w-2xl mx-auto mb-12 group">
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter') onSubmitSearch(query); }}
            placeholder={t.refinePlaceholder}
            className="w-full h-14 bg-white border border-slate-200 rounded-2xl pl-14 pr-6 text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-4 focus:ring-brand/20 focus:border-brand transition-all shadow-sm"
            autoFocus
          />
          <Search className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
        </div>
        {results.length > 0 ? (
          <div className="city-grid">
            {results.map(c => (
              <CityCard
                key={c.id}
                title={c.name}
                tagline={c.tagline}
                image={c.image}
                rating={c.rating}
                onClick={() => onCityClick(c.id)}
              />
            ))}
          </div>
        ) : (
          <div className="text-center py-20">
            <p className="text-slate-400 text-sm font-bold uppercase tracking-widest mb-4">{SITE_TEXT.emptyStates.searchNoMatchHeadline(query)}</p>
            <p className="text-slate-500 text-xs">{SITE_TEXT.emptyStates.searchHelp}</p>
          </div>
        )}
      </section>
    </motion.div>
  );
}

function InfoPageView({ topic, onHome }: { topic: InfoTopic; onHome: () => void }) {
  const content = INFO_CONTENT[topic];
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader eyebrow={SITE_TEXT.infoPage.eyebrow} title={content.title} subtitle={content.intro} />
      <section className="max-w-3xl mx-auto px-4">
        <div className="space-y-6">
          {content.sections.map(s => (
            <div key={s.heading} className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-sm">
              <h3 className="text-base font-black uppercase tracking-tight text-slate-900 mb-3">{s.heading}</h3>
              <p className="text-[14px] text-slate-600 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
        <div className="mt-12 text-center">
          <button
            onClick={onHome}
            className="bg-slate-950 text-white px-8 py-4 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-brand hover:text-slate-950 transition-colors inline-flex items-center gap-3"
          >
            {SITE_TEXT.infoPage.backHomeButton} <ArrowRight size={14} />
          </button>
        </div>
      </section>
    </motion.div>
  );
}

function MatrixVisual({ label, value, level, color }: any) {
  return (
    <div className="space-y-3">
      <div className="flex justify-between items-end">
        <span className="text-[10px] font-bold uppercase tracking-tighter text-white/90">{label}</span>
        <span className={`text-[10px] font-bold ${level === 'HIGH' || level === 'EXTREME' ? 'text-orange-400' : 'text-brand'}`}>{level}</span>
      </div>
      <div className="h-1.5 w-full bg-white/10 rounded-full overflow-hidden">
        <motion.div
          initial={{ width: 0 }}
          animate={{ width: `${value}%` }}
          className={`h-full ${color}`}
        />
      </div>
    </div>
  );
}

// --- Sub-Components ---

function CityCard({ title, tagline, image, rating, onClick }: any) {
  return (
    <motion.div
      whileHover={{ y: -10 }}
      className="group bg-white rounded-[2.5rem] overflow-hidden shadow-xl shadow-slate-200/50 cursor-pointer border border-transparent hover:border-brand/20 transition-all flex flex-col items-center text-center p-2"
      onClick={onClick}
    >
      <div className="w-full aspect-[4/3] relative overflow-hidden rounded-[2rem]">
        <img
          src={image}
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
          alt={title}
        />
        <div className="absolute top-4 right-4 bg-slate-900/90 backdrop-blur px-3 py-1.5 rounded-full font-black text-[10px] text-brand flex items-center gap-1.5 shadow-lg">
          <TrendingUp size={12} />
          {rating}
        </div>
      </div>
      <div className="p-6 w-full">
        <h3 className="text-xl font-black mb-1 text-slate-950 uppercase tracking-tight">{title}</h3>
        <p className="text-slate-400 text-[10px] font-bold uppercase tracking-[0.2em] mb-4">{tagline}</p>
        <div className="flex items-center justify-between border-t border-slate-50 pt-4">
          <div className="flex gap-1.5">
            <div className="w-1.5 h-1.5 rounded-full bg-brand"></div>
            <div className="w-1.5 h-1.5 rounded-full bg-slate-100"></div>
          </div>
          <span className="text-slate-950 font-black text-[10px] flex items-center gap-2 uppercase tracking-widest group-hover:text-brand transition-colors">
            {SITE_TEXT.cityCard.blueprintCta} <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
          </span>
        </div>
      </div>
    </motion.div>
  );
}
