/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * NOTE: Do not edit this file to change website copy.
 * All editable text + content lives in `src/content.tsx`.
 * Edit that file and Vite will hot-reload the change.
 */

import React, { useState, useEffect, useMemo, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Search,
  Train,
  Bus,
  Car,
  Plane,
  Utensils,
  AlertCircle,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  TrendingUp,
  Check,
  X,
  ChevronDown,
  SlidersHorizontal,
  RotateCcw,
  Menu
} from 'lucide-react';
import {
  SITE_TEXT,
  PERSONALITIES,
  MOODS,
  TRAVELER_TYPES,
  SORT_OPTIONS,
  INFO_CONTENT,
  ABOUT_PILLARS,
  DESTINATION_LIST,
  ALL_CITIES_LIST,
  LITE_CITIES,
  getDestination,
  searchDestinations,
  destinationsForPersona,
  type Destination,
  type DestinationSummary,
  type LiteCity,
  type SortId,
  type InfoTopic
} from './content';

const HOME_PAGE_SIZE = 12;   // strict 4×3 grid → 50 cities span 5 pages

// --- View State ---
type View =
  | { kind: 'home' }
  | { kind: 'city'; cityId: string }
  | { kind: 'destinations' }
  | { kind: 'personas' }
  | { kind: 'about' }
  | { kind: 'search'; query: string }
  | { kind: 'info'; topic: InfoTopic };

const INFO_TOPICS: InfoTopic[] = [
  'how-it-works', 'mint-scoring', 'careers', 'travel-tribes',
  'ambassadors', 'support', 'privacy', 'terms', 'cookies'
];

// import.meta.env.BASE_URL always has a trailing slash; normalize to no trailing slash.
const BASE = import.meta.env.BASE_URL.replace(/\/$/, '');

function viewToUrl(v: View): string {
  const path = (() => {
    switch (v.kind) {
      case 'home':         return '/';
      case 'city':         return `/city/${encodeURIComponent(v.cityId)}`;
      case 'destinations': return '/destinations';
      case 'personas':     return '/personas';
      case 'about':        return '/about';
      case 'search':       return v.query ? `/search?q=${encodeURIComponent(v.query)}` : '/search';
      case 'info':         return `/info/${v.topic}`;
    }
  })();
  return BASE + path;
}

function urlToView(pathname: string, search: string): View {
  let p = pathname;
  if (BASE && p.startsWith(BASE)) p = p.slice(BASE.length);
  const segments = p.split('/').filter(Boolean);
  if (segments.length === 0) return { kind: 'home' };
  const [head, ...rest] = segments;
  if (head === 'city' && rest[0]) return { kind: 'city', cityId: decodeURIComponent(rest[0]) };
  if (head === 'destinations')    return { kind: 'destinations' };
  if (head === 'personas')        return { kind: 'personas' };
  if (head === 'about')           return { kind: 'about' };
  if (head === 'search') {
    const q = new URLSearchParams(search).get('q') ?? '';
    return { kind: 'search', query: q };
  }
  if (head === 'info' && rest[0] && (INFO_TOPICS as string[]).includes(rest[0])) {
    return { kind: 'info', topic: rest[0] as InfoTopic };
  }
  return { kind: 'home' };
}

export default function App() {
  const [view, setView] = useState<View>(() =>
    urlToView(window.location.pathname, window.location.search)
  );
  const [activePersonality, setActivePersonality] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');
  const [loginOpen, setLoginOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const heroSearchRef = useRef<HTMLInputElement>(null);

  // Seed the initial history entry so a future popstate has a state to restore to.
  useEffect(() => {
    if (window.history.state == null) {
      window.history.replaceState(view, '', viewToUrl(view));
    }
    const onPop = (e: PopStateEvent) => {
      const next: View = e.state ?? urlToView(window.location.pathname, window.location.search);
      setView(next);
    };
    window.addEventListener('popstate', onPop);
    return () => window.removeEventListener('popstate', onPop);
  }, []);

  const navigate = (next: View) => {
    setView(next);
    const url = viewToUrl(next);
    if (url !== window.location.pathname + window.location.search) {
      window.history.pushState(next, '', url);
    }
  };

  const openCity = (cityId: string) => {
    const isKnown = !!getDestination(cityId) || LITE_CITIES.some(c => c.id === cityId);
    if (!isKnown) {
      showToast(SITE_TEXT.toasts.cityComingSoon(cityId));
      return;
    }
    navigate({ kind: 'city', cityId });
    window.scrollTo(0, 0);
  };

  const submitSearch = (q: string) => {
    const trimmed = q.trim();
    navigate({ kind: 'search', query: trimmed });
  };

  const focusHeroSearch = () => {
    if (view.kind !== 'home') {
      navigate({ kind: 'home' });
      setTimeout(() => heroSearchRef.current?.focus(), 350);
    } else {
      heroSearchRef.current?.focus();
      heroSearchRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  };

  const showToast = (message: string) => {
    setToast(message);
  };

  useEffect(() => {
    if (!toast) return;
    const t = setTimeout(() => setToast(null), 2800);
    return () => clearTimeout(t);
  }, [toast]);

  const selectedCity = view.kind === 'city' ? getDestination(view.cityId) : null;
  const selectedLiteCity = view.kind === 'city' && !selectedCity
    ? (LITE_CITIES.find(c => c.id === view.cityId) ?? null)
    : null;

  return (
    <div className="min-h-screen flex flex-col bg-surface-bg">
      {/* Navigation */}
      <nav className="w-full bg-slate-950 border-b border-slate-900 z-50">
        <div className="max-w-7xl mx-auto px-4 h-20 flex items-center justify-between">
          <div
            className="flex items-center gap-3 cursor-pointer group"
            onClick={() => navigate({ kind: 'home' })}
          >
            <Logo size="md" />
            <span className="font-display text-2xl font-black text-white tracking-tighter">{SITE_TEXT.brand.name}<span className="text-brand">{SITE_TEXT.brand.nameAccent}</span></span>
          </div>
          <div className="hidden md:flex items-center gap-8 text-sm font-bold text-slate-400">
            {/* City-page-only live search; placed before the Home button. */}
            {view.kind === 'city' && (
              <NavSearch
                query={searchQuery}
                setQuery={setSearchQuery}
                onCityClick={openCity}
              />
            )}
            <NavLink active={view.kind === 'home'}         onClick={() => navigate({ kind: 'home' })}>{SITE_TEXT.nav.home}</NavLink>
            <NavLink active={view.kind === 'destinations'} onClick={() => navigate({ kind: 'destinations' })}>{SITE_TEXT.nav.destinations}</NavLink>
            <NavLink active={view.kind === 'personas'}     onClick={() => navigate({ kind: 'personas' })}>{SITE_TEXT.nav.personaGuides}</NavLink>
            <NavLink active={view.kind === 'about'}        onClick={() => navigate({ kind: 'about' })}>{SITE_TEXT.nav.about}</NavLink>
            <button
              onClick={() => setLoginOpen(true)}
              className="bg-brand/10 text-brand px-6 py-2.5 rounded-xl border border-brand/20 hover:bg-brand hover:text-slate-950 transition-all font-black"
            >
              {SITE_TEXT.nav.login}
            </button>
          </div>
          {/* Mobile-only nav controls: search icon (jumps to hero search)
              and a hamburger that opens the off-canvas nav drawer. */}
          <div className="md:hidden flex items-center gap-4">
            <button
              type="button"
              onClick={focusHeroSearch}
              aria-label="Search"
              className="text-white hover:text-brand transition-colors"
            >
              <Search size={24} />
            </button>
            <button
              type="button"
              onClick={() => setMobileMenuOpen(true)}
              aria-label="Open menu"
              className="text-white hover:text-brand transition-colors"
            >
              <Menu size={26} />
            </button>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="flex-1">
        {view.kind === 'home' && (
          <HomeView
            onCityClick={openCity}
            activePersonality={activePersonality}
            setActivePersonality={setActivePersonality}
            searchQuery={searchQuery}
            setSearchQuery={setSearchQuery}
            onSubmitSearch={submitSearch}
            heroSearchRef={heroSearchRef}
          />
        )}
        {view.kind === 'city' && selectedCity && (
          <CityView
            city={selectedCity}
            activePersonality={activePersonality}
            setActivePersonality={setActivePersonality}
          />
        )}
        {view.kind === 'city' && !selectedCity && selectedLiteCity && (
          <LiteCityView
            city={selectedLiteCity}
            onExploreVerified={() => navigate({ kind: 'destinations' })}
          />
        )}
        {view.kind === 'destinations' && (
          <DestinationsView onCityClick={openCity} />
        )}
        {view.kind === 'personas' && (
          <PersonaGuidesView onCityClick={openCity} />
        )}
        {view.kind === 'about' && (
          <AboutView onExploreClick={() => navigate({ kind: 'destinations' })} />
        )}
        {view.kind === 'search' && (
          <SearchView
            initialQuery={view.query}
            onCityClick={openCity}
            onSubmitSearch={submitSearch}
          />
        )}
        {view.kind === 'info' && (
          <InfoPageView
            topic={view.topic}
            onHome={() => navigate({ kind: 'home' })}
          />
        )}
      </main>

      {/* Back-to-top action — sits in-flow just before the footer (per the
          changes.docx note) rather than as a floating widget. Smooth-scrolls
          the page to the very top. */}
      <div className="w-full flex justify-center py-10 bg-surface-bg">
        <button
          type="button"
          onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          aria-label={SITE_TEXT.backToTop.ariaLabel}
          className="w-12 h-12 rounded-full bg-brand text-slate-950 flex items-center justify-center shadow-lg shadow-brand/30 hover:bg-white transition-colors"
        >
          <ArrowUp size={20} strokeWidth={3} />
        </button>
      </div>

      {/* Footer */}
      <footer className="bg-slate-950 text-slate-400 pt-20 pb-10 border-t border-slate-900">
        <div className="max-w-7xl mx-auto px-4">
          {/* Footer is a 3-column grid on md+. Brand + Community now share
              column 1 (Community moved up out of column 3) so the empty
              area below the short brand blurb is filled. Platform stays in
              column 2 and Newsletter in column 3. On mobile everything
              stacks single-column with the same gap. */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-12 mb-16">
            <div className="space-y-10">
              <div className="space-y-6">
                <div
                  className="flex items-center gap-2 cursor-pointer"
                  onClick={() => navigate({ kind: 'home' })}
                >
                  <Logo size="sm" />
                  <span className="font-display text-xl font-bold text-white tracking-tight">{SITE_TEXT.brand.name}{SITE_TEXT.brand.nameAccent}</span>
                </div>
                <p className="text-sm leading-relaxed opacity-60">{SITE_TEXT.footer.brandBlurb}</p>
              </div>

              <div>
                <h4 className="text-white font-bold mb-6 text-sm uppercase tracking-widest">{SITE_TEXT.footer.communityHeading}</h4>
                <ul className="space-y-4 text-xs font-bold">
                  {SITE_TEXT.footer.communityLinks.map(link => (
                    <li key={link.label}>
                      <FooterLink onClick={() => navigate(link.view === 'info' ? { kind: 'info', topic: link.topic } : { kind: link.view })}>
                        {link.label}
                      </FooterLink>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div>
              <h4 className="text-white font-bold mb-6 text-sm uppercase tracking-widest">{SITE_TEXT.footer.platformHeading}</h4>
              <ul className="space-y-4 text-xs font-bold">
                {SITE_TEXT.footer.platformLinks.map(link => (
                  <li key={link.label}>
                    <FooterLink onClick={() => navigate(link.view === 'info' ? { kind: 'info', topic: link.topic } : { kind: link.view })}>
                      {link.label}
                    </FooterLink>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h4 className="text-white font-bold mb-6 text-sm uppercase tracking-widest text-brand">{SITE_TEXT.footer.newsletterHeading}</h4>
              <p className="text-xs mb-4 opacity-60">{SITE_TEXT.footer.newsletterBlurb}</p>
              <NewsletterForm onSubscribed={(email) => showToast(SITE_TEXT.toasts.subscribed(email))} onInvalid={() => showToast(SITE_TEXT.toasts.invalidEmail)} />
            </div>
          </div>

          <div className="pt-8 border-t border-slate-900 flex flex-col md:flex-row items-center justify-between gap-4 text-[10px] font-bold uppercase tracking-widest">
            <p>{SITE_TEXT.footer.copyright}</p>
            <div className="flex gap-6">
              {SITE_TEXT.footer.legalLinks.map(link => (
                <React.Fragment key={link.label}>
                  <FooterLink onClick={() => navigate({ kind: 'info', topic: link.topic })}>
                    {link.label}
                  </FooterLink>
                </React.Fragment>
              ))}
            </div>
          </div>
        </div>
      </footer>

      {/* Mobile nav drawer — opens from the right via the hamburger button
          in the navbar. Mirrors the desktop nav links plus Login. */}
      <AnimatePresence>
        {mobileMenuOpen && (
          <MobileMenu
            view={view}
            onClose={() => setMobileMenuOpen(false)}
            onNavigate={(v) => { setMobileMenuOpen(false); navigate(v); }}
            onLogin={() => { setMobileMenuOpen(false); setLoginOpen(true); }}
          />
        )}
      </AnimatePresence>

      {/* Login Modal */}
      <AnimatePresence>
        {loginOpen && (
          <LoginModal
            onClose={() => setLoginOpen(false)}
            onSuccess={(email) => {
              setLoginOpen(false);
              showToast(SITE_TEXT.toasts.loginWelcome(email.split('@')[0]));
            }}
          />
        )}
      </AnimatePresence>

      {/* Toast */}
      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ y: 60, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 60, opacity: 0 }}
            className="fixed bottom-8 left-1/2 -translate-x-1/2 z-[60] bg-slate-950 text-white px-6 py-4 rounded-2xl shadow-2xl shadow-slate-950/40 border border-slate-800 flex items-center gap-3"
          >
            <Check size={16} className="text-brand" strokeWidth={3} />
            <span className="text-xs font-bold uppercase tracking-widest">{toast}</span>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// --- Reusable link components ---

// Centralised brand mark. Renders the REVIEWMINT logo PNG (served from
// /public via Vite's BASE_URL so it works on both the dev server and the
// GitHub Pages deployment).
//
// The PNG ships with its own black background, which would otherwise
// blend into the dark slate-950 navbar/footer and lose all definition.
// To preserve the mint-green brand presence the old text-tile gave us,
// we wrap the image in a thin brand-coloured ring (plus a soft brand
// shadow on the md variant) so the logo tile stays visually distinct
// against any dark surface.
function Logo({ size = 'md' }: { size?: 'sm' | 'md' }) {
  const dim = size === 'sm'
    ? 'w-8 h-8 rounded-lg ring-1 ring-brand/70'
    : 'w-10 h-10 rounded-xl ring-2 ring-brand shadow-lg shadow-brand/30';
  return (
    <div className={`${dim} overflow-hidden bg-slate-950 shrink-0`}>
      <img
        src={`${import.meta.env.BASE_URL}logo.png`}
        alt={`${SITE_TEXT.brand.name}${SITE_TEXT.brand.nameAccent} logo`}
        className="w-full h-full object-cover"
        draggable={false}
      />
    </div>
  );
}

function NavLink({ children, onClick, active }: { children: React.ReactNode; onClick: () => void; active?: boolean }) {
  return (
    <a
      href="#"
      onClick={(e) => { e.preventDefault(); onClick(); }}
      className={`hover:text-brand transition-colors ${active ? 'text-brand' : ''}`}
    >
      {children}
    </a>
  );
}

function FooterLink({ children, onClick }: { children: React.ReactNode; onClick: () => void }) {
  return (
    <a
      href="#"
      onClick={(e) => { e.preventDefault(); onClick(); }}
      className="hover:text-brand"
    >
      {children}
    </a>
  );
}

function NewsletterForm({ onSubscribed, onInvalid }: { onSubscribed: (email: string) => void; onInvalid: () => void }) {
  const [email, setEmail] = useState('');
  const submit = () => {
    const e = email.trim();
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)) {
      onInvalid();
      return;
    }
    onSubscribed(e);
    setEmail('');
  };
  return (
    <div className="flex gap-2">
      <input
        type="email"
        placeholder={SITE_TEXT.footer.newsletterPlaceholder}
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        onKeyDown={(e) => { if (e.key === 'Enter') submit(); }}
        className="bg-slate-900 border border-slate-800 rounded-lg px-4 py-2 text-xs focus:outline-none focus:border-brand w-full"
      />
      <button
        onClick={submit}
        className="bg-brand text-slate-950 px-4 py-2 rounded-lg text-xs font-bold"
      >
        {SITE_TEXT.footer.newsletterButton}
      </button>
    </div>
  );
}

// Off-canvas mobile navigation drawer. Slides in from the right; backdrop
// click and the X button both close it. Active link mirrors the desktop
// navbar's active styling for consistency.
function MobileMenu({ view, onClose, onNavigate, onLogin }: any) {
  const items: { label: string; view: View; isActive: boolean }[] = [
    { label: SITE_TEXT.nav.home,          view: { kind: 'home' },         isActive: view.kind === 'home' },
    { label: SITE_TEXT.nav.destinations,  view: { kind: 'destinations' }, isActive: view.kind === 'destinations' },
    { label: SITE_TEXT.nav.personaGuides, view: { kind: 'personas' },     isActive: view.kind === 'personas' },
    { label: SITE_TEXT.nav.about,         view: { kind: 'about' },        isActive: view.kind === 'about' },
  ];
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[65] bg-slate-950/70 backdrop-blur-md md:hidden"
      onClick={onClose}
    >
      <motion.div
        initial={{ x: '100%' }}
        animate={{ x: 0 }}
        exit={{ x: '100%' }}
        transition={{ type: 'spring', damping: 28, stiffness: 240 }}
        onClick={(e) => e.stopPropagation()}
        className="absolute top-0 right-0 h-full w-72 max-w-[85vw] bg-slate-950 border-l border-slate-900 shadow-2xl flex flex-col"
      >
        <div className="flex items-center justify-between p-6 border-b border-slate-900">
          <div className="flex items-center gap-2">
            <Logo size="sm" />
            <span className="font-display text-lg font-black text-white tracking-tighter">{SITE_TEXT.brand.name}<span className="text-brand">{SITE_TEXT.brand.nameAccent}</span></span>
          </div>
          <button type="button" onClick={onClose} className="text-slate-400 hover:text-white" aria-label="Close menu">
            <X size={20} />
          </button>
        </div>
        <nav className="flex-1 px-4 py-6 flex flex-col gap-1">
          {items.map(it => (
            <button
              key={it.label}
              type="button"
              onClick={() => onNavigate(it.view)}
              className={`text-left px-4 py-3 rounded-xl text-sm font-bold uppercase tracking-widest transition-colors ${
                it.isActive ? 'bg-brand/10 text-brand' : 'text-slate-400 hover:text-white hover:bg-slate-900'
              }`}
            >
              {it.label}
            </button>
          ))}
          <button
            type="button"
            onClick={onLogin}
            className="mt-4 w-full bg-brand text-slate-950 px-6 py-3 rounded-xl font-black uppercase tracking-widest text-xs hover:bg-white transition-colors"
          >
            {SITE_TEXT.nav.login}
          </button>
        </nav>
      </motion.div>
    </motion.div>
  );
}

function LoginModal({ onClose, onSuccess }: { onClose: () => void; onSuccess: (email: string) => void }) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim() || !password.trim()) return;
    onSuccess(email.trim());
  };
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[70] bg-slate-950/70 backdrop-blur-md flex items-center justify-center p-4"
      onClick={onClose}
    >
      <motion.form
        initial={{ y: 30, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        exit={{ y: 30, opacity: 0 }}
        onClick={(e) => e.stopPropagation()}
        onSubmit={submit}
        className="bg-slate-950 border border-slate-800 rounded-[2rem] p-10 w-full max-w-md shadow-2xl"
      >
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-3">
            <Logo size="md" />
            <span className="font-display text-xl font-black text-white tracking-tighter">{SITE_TEXT.loginModal.title}</span>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-slate-500 hover:text-white transition-colors"
            aria-label="Close login"
          >
            <X size={20} />
          </button>
        </div>
        <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-slate-500 mb-6">{SITE_TEXT.loginModal.meta}</p>
        <label className="block text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">{SITE_TEXT.loginModal.emailLabel}</label>
        <input
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder={SITE_TEXT.loginModal.emailPlaceholder}
          className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand mb-4"
          autoFocus
        />
        <label className="block text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">{SITE_TEXT.loginModal.passwordLabel}</label>
        <input
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          placeholder={SITE_TEXT.loginModal.passwordPlaceholder}
          className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand mb-8"
        />
        <button
          type="submit"
          className="w-full bg-brand text-slate-950 font-black uppercase tracking-widest text-xs py-4 rounded-xl hover:bg-white transition-colors"
        >
          {SITE_TEXT.loginModal.submitButton}
        </button>
        <p className="text-[10px] text-slate-500 mt-6 text-center">{SITE_TEXT.loginModal.fineprint}</p>
      </motion.form>
    </motion.div>
  );
}

// --- Views ---

function HomeView({
  onCityClick,
  activePersonality,
  setActivePersonality,
  searchQuery,
  setSearchQuery,
  onSubmitSearch,
  heroSearchRef
}: {
  onCityClick: (id: string) => void;
  activePersonality: string;
  setActivePersonality: (p: string) => void;
  searchQuery: string;
  setSearchQuery: (q: string) => void;
  onSubmitSearch: (q: string) => void;
  heroSearchRef: React.RefObject<HTMLInputElement | null>;
}) {
  // --- Discovery filter + sort state (works across all pages) ---
  // Multi-select within each group; "All" is no longer a personality
  // option — it lives on its own pill (see FilterBar) that resets state.
  const [personalities, setPersonalities] = useState<string[]>([]);
  const [moods, setMoods] = useState<string[]>([]);
  const [travelers, setTravelers] = useState<string[]>([]);
  const [sortId, setSortId] = useState<SortId>('relevance');

  const filteredCities = useMemo(
    () => filterAndSortCities(ALL_CITIES_LIST, { personalities, moods, travelers, sortId }),
    [personalities, moods, travelers, sortId]
  );

  const [page, setPage] = useState(1);
  useEffect(() => { setPage(1); }, [personalities, moods, travelers, sortId]);
  const pageCount = Math.max(1, Math.ceil(filteredCities.length / HOME_PAGE_SIZE));
  const safePage = Math.min(page, pageCount);
  const visibleCities = filteredCities.slice((safePage - 1) * HOME_PAGE_SIZE, safePage * HOME_PAGE_SIZE);

  // Pagination should land the user on the first card of the new page,
  // not leave them stranded at the bottom where the Prev/Next buttons sit.
  const gridRef = useRef<HTMLDivElement>(null);
  const goToPage = (p: number) => {
    setPage(p);
    gridRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  const toggleIn = (setter: React.Dispatch<React.SetStateAction<string[]>>) => (v: string) =>
    setter(prev => prev.includes(v) ? prev.filter(x => x !== v) : [...prev, v]);
  const togglePersonality = toggleIn(setPersonalities);
  const toggleMood        = toggleIn(setMoods);
  const toggleTraveler    = toggleIn(setTravelers);
  const clearFilters = () => { setPersonalities([]); setMoods([]); setTravelers([]); };
  const hasActiveFilters = personalities.length > 0 || moods.length > 0 || travelers.length > 0;

  // Live, button-free search preview strip (partial / prefix / progressive).
  const liveResults = useMemo(
    () => searchQuery.trim() ? liveSearch(searchQuery) : [],
    [searchQuery]
  );

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="pb-20"
    >
      <section className="relative h-[450px] flex items-center justify-center text-center overflow-hidden">
        <div className="absolute inset-0 z-0">
          <img
            src="https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=2076&auto=format&fit=crop"
            className="w-full h-full object-cover brightness-[0.3]"
            alt="Hero Background"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-slate-950/20 to-slate-950/40"></div>
        </div>
        <div className="relative z-10 max-w-4xl px-4">
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-brand/10 border border-brand/20 text-brand text-[10px] font-black uppercase tracking-[0.3em] px-4 py-2 rounded-full w-fit mx-auto mb-8 backdrop-blur-md"
          >
            {SITE_TEXT.hero.eyebrow}
          </motion.div>
          <motion.h1
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="text-5xl md:text-7xl text-white mb-8 font-black tracking-tighter uppercase"
          >
            {SITE_TEXT.hero.titleLine1} <span className="text-brand">{SITE_TEXT.hero.titleAccent}</span><br />
            {SITE_TEXT.hero.titleLine2} <span className="italic">{SITE_TEXT.hero.titleItalic}</span>
          </motion.h1>
          <div className="relative max-w-xl mx-auto group">
            <input
              ref={heroSearchRef}
              type="text"
              placeholder={SITE_TEXT.hero.searchPlaceholder}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') onSubmitSearch(searchQuery); }}
              className="w-full h-16 bg-white/10 backdrop-blur-xl border border-white/10 rounded-2xl pl-16 pr-6 text-white placeholder:text-white/40 focus:outline-none focus:ring-4 focus:ring-brand/30 transition-all shadow-2xl group-hover:bg-white/20"
            />
            <button
              type="button"
              onClick={() => onSubmitSearch(searchQuery)}
              className="absolute left-6 top-1/2 -translate-y-1/2 text-white/50 hover:text-brand transition-colors"
              aria-label="Submit search"
            >
              <Search size={24} />
            </button>
          </div>
        </div>
      </section>

      {/* Pulled up into the hero (preserves the signature overlap the old
          persona strip had). Holds the live-search preview + filter bar. */}
      <section className="max-w-7xl mx-auto px-4 mt-[-40px] relative z-20">
        {/* Live, button-free search preview: a horizontal scrollable strip of
            matching city cards that updates as the user types. */}
        <AnimatePresence>
          {searchQuery.trim() && (
            <motion.div
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="bg-white rounded-[2rem] p-5 shadow-xl shadow-slate-200/50 border border-slate-100/60 mb-6"
            >
              <div className="flex items-center justify-between mb-4 px-1">
                <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">
                  {SITE_TEXT.filterBar.liveSearchHint} · "{searchQuery.trim()}"
                </span>
                <span className="text-[10px] font-black uppercase tracking-widest text-brand">
                  {liveResults.length}
                </span>
              </div>
              {liveResults.length > 0 ? (
                <div className="live-strip">
                  {liveResults.map(c => (
                    <LiveResultCard
                      key={c.id}
                      title={c.name}
                      tagline={c.tagline}
                      image={c.image}
                      rating={c.rating}
                      onClick={() => onCityClick(c.id)}
                    />
                  ))}
                </div>
              ) : (
                <p className="text-[11px] font-bold uppercase tracking-widest text-slate-300 px-1 py-4">
                  {SITE_TEXT.filterBar.noLiveMatches}
                </p>
              )}
            </motion.div>
          )}
        </AnimatePresence>

        <FilterBar
          personalities={personalities}
          togglePersonality={togglePersonality}
          moods={moods}
          toggleMood={toggleMood}
          travelers={travelers}
          toggleTraveler={toggleTraveler}
          sortId={sortId}
          setSortId={setSortId}
          resultCount={filteredCities.length}
          hasActiveFilters={hasActiveFilters}
          onClear={clearFilters}
        />

        <div ref={gridRef} className="city-grid">
          {visibleCities.map(c => (
            <CityCard
              key={c.id}
              title={c.name}
              tagline={c.tagline}
              image={c.image}
              rating={c.rating}
              onClick={() => onCityClick(c.id)}
            />
          ))}
        </div>
        {filteredCities.length === 0 && (
          <div className="text-center py-20 text-slate-400 text-sm font-bold uppercase tracking-widest">
            {SITE_TEXT.emptyStates.homePersonaNoMatch}
          </div>
        )}

        {pageCount > 1 && (
          <Pagination page={safePage} pageCount={pageCount} onChange={goToPage} />
        )}
      </section>
    </motion.div>
  );
}

// --- Discovery filtering + sorting (shared by the homepage filter bar) ---

function filterAndSortCities(
  list: DestinationSummary[],
  opts: { personalities: string[]; moods: string[]; travelers: string[]; sortId: SortId }
): DestinationSummary[] {
  const { personalities, moods, travelers, sortId } = opts;
  // Within each group: OR (city matches if it shares any selected tag).
  // Across groups: AND (city must pass every active group).
  let out = list.filter(c =>
    (personalities.length === 0 || personalities.some(p => c.personalities.includes(p))) &&
    (moods.length        === 0 || moods.some(m => c.moods.includes(m))) &&
    (travelers.length    === 0 || travelers.some(t => c.travelerType.includes(t)))
  );
  const byName = (a: DestinationSummary, b: DestinationSummary) => a.name.localeCompare(b.name);
  switch (sortId) {
    case 'score-desc': out = [...out].sort((a, b) => b.score - a.score); break;
    case 'score-asc':  out = [...out].sort((a, b) => a.score - b.score); break;
    case 'az':         out = [...out].sort(byName); break;
    case 'za':         out = [...out].sort((a, b) => byName(b, a)); break;
    case 'newest':     out = [...out].sort((a, b) => b.order - a.order); break;
    case 'oldest':     out = [...out].sort((a, b) => a.order - b.order); break;
    case 'relevance':
    default:           break;   // keep natural catalogue order
  }
  return out;
}

// Intelligent live matcher: prefix matches first, then partial/progressive
// matches across name, id and tagline. Capped for a tidy strip.
function liveSearch(q: string): DestinationSummary[] {
  const s = q.trim().toLowerCase();
  if (!s) return [];
  const starts: DestinationSummary[] = [];
  const contains: DestinationSummary[] = [];
  for (const c of ALL_CITIES_LIST) {
    const name = c.name.toLowerCase();
    if (name.startsWith(s)) starts.push(c);
    else if (name.includes(s) || c.id.toLowerCase().includes(s) || c.tagline.toLowerCase().includes(s)) contains.push(c);
  }
  return [...starts, ...contains].slice(0, 12);
}

function FilterChip({ active, onClick, children, accent }: any) {
  const on = accent === 'brand'
    ? 'bg-brand text-slate-950 shadow-lg shadow-brand/20'
    : 'bg-slate-900 text-white shadow-lg shadow-slate-900/20';
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex items-center gap-2 px-5 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap ${
        active ? on : 'bg-slate-50 text-slate-500 hover:bg-slate-100'
      }`}
    >
      {children}
    </button>
  );
}

// Compact premium filter bar: a global "All" reset pill plus three
// collapsible dropdown groups (Personality / Travel Type / Traveler
// Type) — only one expanded at a time. Selections are multi-select
// within each group; cities matching any selected tag in a group pass.
function FilterBar({
  personalities, togglePersonality, moods, toggleMood, travelers, toggleTraveler,
  sortId, setSortId, resultCount, hasActiveFilters, onClear
}: any) {
  const t = SITE_TEXT.filterBar;
  const [openGroup, setOpenGroup] = useState<null | 'personality' | 'mood' | 'traveler'>(null);
  const barRef = useRef<HTMLDivElement>(null);

  // Close the dropdown panel on outside click.
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (barRef.current && !barRef.current.contains(e.target as Node)) setOpenGroup(null);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const groupBtn = (id: 'personality' | 'mood' | 'traveler', label: string, count: number) => (
    <button
      type="button"
      onClick={() => setOpenGroup(g => g === id ? null : id)}
      className={`flex items-center gap-2 px-5 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap ${
        openGroup === id
          ? 'bg-slate-900 text-white shadow-lg shadow-slate-900/20'
          : count > 0
            ? 'bg-brand text-slate-950 shadow-lg shadow-brand/20'
            : 'bg-slate-50 text-slate-500 hover:bg-slate-100'
      }`}
    >
      {label}
      {count > 0 && <span className="bg-white/30 px-1.5 py-0.5 rounded text-[9px]">{count}</span>}
      <ChevronDown size={12} className={`transition-transform ${openGroup === id ? 'rotate-180' : ''}`} />
    </button>
  );

  return (
    <div ref={barRef} className="bg-white rounded-[2.5rem] p-6 md:p-8 shadow-xl shadow-slate-200/40 mb-12 border border-slate-100/50">
      {/* Top row: result count · global All reset · 3 group buttons · sort · clear */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 bg-slate-950 rounded-xl flex items-center justify-center text-brand shrink-0">
            <SlidersHorizontal size={16} />
          </div>
          <span className="text-[11px] font-black uppercase tracking-widest text-slate-900">
            {t.results(resultCount)}
          </span>
        </div>

        {/* Global "All" reset — highlighted when no filters are active.
            Clicking it clears every group; selecting any filter implicitly
            exits "All" mode (it becomes un-highlighted). */}
        <button
          type="button"
          onClick={onClear}
          className={`ml-2 flex items-center gap-2 px-5 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap ${
            !hasActiveFilters
              ? 'bg-slate-900 text-white shadow-lg shadow-slate-900/20'
              : 'bg-slate-50 text-slate-500 hover:bg-slate-100'
          }`}
        >
          <TrendingUp size={14} />{t.allLabel}
        </button>

        {groupBtn('personality', t.personalityLabel, personalities.length)}
        {groupBtn('mood',        t.moodLabel,        moods.length)}
        {groupBtn('traveler',    t.travelerLabel,    travelers.length)}

        {/* Sort dropdown. On mobile it sits inline with the group buttons
            (no auto-margin) with tighter padding so it fits alongside the
            Traveler Type chip on a single row. Desktop pushes it right
            via ml-auto and keeps the fuller "Sort By: …" labels. */}
        <div className="relative md:ml-auto">
          <select
            value={sortId}
            onChange={(e) => setSortId(e.target.value as SortId)}
            className="appearance-none bg-slate-50 border border-slate-100 rounded-xl pl-3 pr-8 py-2 md:pl-4 md:pr-10 md:py-2.5 text-[10px] font-black uppercase tracking-widest text-slate-700 focus:outline-none focus:border-brand cursor-pointer hover:bg-slate-100 transition-colors"
            aria-label={t.sortLabel}
          >
            {SORT_OPTIONS.map(o => (
              <option key={o.id} value={o.id}>{o.label}</option>
            ))}
          </select>
          <ChevronDown size={14} className="absolute right-2 md:right-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
        </div>

        {hasActiveFilters && (
          <button
            type="button"
            onClick={onClear}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest text-rose-500 bg-rose-50 hover:bg-rose-100 transition-colors"
          >
            <RotateCcw size={13} /> {t.clearFilters}
          </button>
        )}
      </div>

      {/* Expandable panel — only the currently-open group renders here. */}
      <AnimatePresence>
        {openGroup && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden"
          >
            <div className="flex flex-wrap gap-2 pt-5 mt-5 border-t border-slate-50">
              {openGroup === 'personality' && PERSONALITIES.filter(p => p.id !== 'All').map(p => (
                <FilterChip key={p.id} active={personalities.includes(p.id)} onClick={() => togglePersonality(p.id)}>
                  {p.icon}{p.id}
                </FilterChip>
              ))}
              {openGroup === 'mood' && MOODS.map(m => (
                <FilterChip key={m} active={moods.includes(m)} accent="brand" onClick={() => toggleMood(m)}>
                  {m}
                </FilterChip>
              ))}
              {openGroup === 'traveler' && TRAVELER_TYPES.map(tv => (
                <FilterChip key={tv} active={travelers.includes(tv)} onClick={() => toggleTraveler(tv)}>
                  {tv}
                </FilterChip>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Removable active-chip row, mirrors the previous design. */}
      {hasActiveFilters && (
        <div className="flex items-center gap-2 flex-wrap pt-5 mt-5 border-t border-slate-50">
          <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 mr-1">{t.activeLabel}</span>
          {personalities.map((p: string) => <ActiveChip key={p} label={p} onRemove={() => togglePersonality(p)} />)}
          {moods.map((m: string)            => <ActiveChip key={m} label={m} onRemove={() => toggleMood(m)} />)}
          {travelers.map((tv: string)       => <ActiveChip key={tv} label={tv} onRemove={() => toggleTraveler(tv)} />)}
        </div>
      )}
    </div>
  );
}

function ActiveChip({ label, onRemove }: any) {
  return (
    <span className="flex items-center gap-1.5 bg-slate-900 text-white pl-3 pr-2 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest">
      {label}
      <button type="button" onClick={onRemove} aria-label={`Remove ${label}`} className="hover:text-brand transition-colors">
        <X size={12} strokeWidth={3} />
      </button>
    </span>
  );
}

function LiveResultCard({ title, tagline, image, rating, onClick }: any) {
  return (
    <motion.div
      whileHover={{ y: -4 }}
      onClick={onClick}
      className="w-44 bg-white rounded-2xl overflow-hidden border border-slate-100 shadow-sm cursor-pointer group"
    >
      <div className="relative w-full aspect-[4/3] overflow-hidden">
        <img src={image} alt={title} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" />
        <div className="absolute top-2 right-2 bg-slate-900/90 backdrop-blur px-2 py-1 rounded-full font-black text-[9px] text-brand flex items-center gap-1">
          <TrendingUp size={10} />{rating}
        </div>
      </div>
      <div className="p-3">
        <h4 className="text-xs font-black uppercase tracking-tight text-slate-950 truncate">{title}</h4>
        <p className="text-[9px] font-bold uppercase tracking-widest text-slate-400 truncate mt-0.5">{tagline}</p>
      </div>
    </motion.div>
  );
}

// Compact city-page navbar search with the same live-result dropdown logic
// used by the homepage hero. Renders only on city pages (gated by the
// caller). Closes on outside click; clicking a result navigates directly.
function NavSearch({ query, setQuery, onCityClick }: any) {
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement>(null);
  const results = useMemo(() => query.trim() ? liveSearch(query) : [], [query]);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const go = (id: string) => {
    setQuery('');
    setOpen(false);
    onCityClick(id);
  };

  return (
    <div ref={wrapRef} className="relative">
      <div className="relative w-[240px]">
        <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" />
        <input
          type="text"
          value={query}
          onChange={e => { setQuery(e.target.value); setOpen(true); }}
          onFocus={() => setOpen(true)}
          placeholder={SITE_TEXT.nav.citySearchPlaceholder}
          className="w-full h-10 bg-slate-900/70 border border-slate-800 rounded-xl pl-9 pr-3 text-xs text-white placeholder:text-slate-500 focus:outline-none focus:border-brand transition-colors"
        />
      </div>
      <AnimatePresence>
        {open && query.trim() && (
          <motion.div
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 4 }}
            className="absolute left-0 right-0 mt-2 bg-white rounded-2xl shadow-2xl shadow-slate-950/40 border border-slate-100 overflow-hidden z-[60] max-h-80 overflow-y-auto"
          >
            {results.length > 0 ? (
              results.slice(0, 8).map(c => (
                <button
                  key={c.id}
                  type="button"
                  onClick={() => go(c.id)}
                  className="w-full text-left flex items-center gap-3 px-3 py-2 hover:bg-slate-50 transition-colors border-b border-slate-50 last:border-b-0"
                >
                  <div className="w-10 h-10 rounded-lg overflow-hidden shrink-0">
                    <img src={c.image} alt={c.name} className="w-full h-full object-cover" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="text-[11px] font-black uppercase tracking-tight text-slate-900 truncate">{c.name}</div>
                    <div className="text-[9px] font-bold uppercase tracking-widest text-slate-400 truncate">{c.tagline}</div>
                  </div>
                  <span className="text-[9px] font-black text-brand shrink-0">{c.rating}</span>
                </button>
              ))
            ) : (
              <div className="px-3 py-4 text-[10px] font-bold uppercase tracking-widest text-slate-300 text-center">
                {SITE_TEXT.filterBar.noLiveMatches}
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function Pagination({ page, pageCount, onChange }: { page: number; pageCount: number; onChange: (p: number) => void }) {
  const prevDisabled = page <= 1;
  const nextDisabled = page >= pageCount;
  const btn = "px-5 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest border transition-all";
  return (
    <div className="flex items-center justify-center gap-4 mt-12">
      <button
        type="button"
        onClick={() => onChange(page - 1)}
        disabled={prevDisabled}
        className={`${btn} ${prevDisabled ? 'border-slate-100 text-slate-300 cursor-not-allowed' : 'border-slate-200 text-slate-700 hover:border-brand hover:text-brand'}`}
      >
        Prev
      </button>
      <span className="text-[10px] font-black uppercase tracking-widest text-slate-500">
        Page {page} of {pageCount}
      </span>
      <button
        type="button"
        onClick={() => onChange(page + 1)}
        disabled={nextDisabled}
        className={`${btn} ${nextDisabled ? 'border-slate-100 text-slate-300 cursor-not-allowed' : 'border-slate-200 text-slate-700 hover:border-brand hover:text-brand'}`}
      >
        Next
      </button>
    </div>
  );
}

function CityView({ city, activePersonality, setActivePersonality }: { city: Destination, activePersonality: string, setActivePersonality: (p: string) => void }) {
  const combinedEffort = (city.matrix.money + city.matrix.fatigue) / 2;
  const t = SITE_TEXT.cityDetail;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="max-w-[1440px] mx-auto px-4 py-8"
    >
      {/* Back to the previous page. window.history.back() triggers the
          existing popstate handler in <App>, so view state stays in sync
          with the URL — works the same on mobile and desktop. */}
      <button
        type="button"
        onClick={() => window.history.back()}
        className="flex items-center gap-2 mb-6 px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest text-slate-500 bg-white border border-slate-100 hover:text-brand hover:border-brand shadow-sm transition-colors"
      >
        <ArrowLeft size={14} /> {SITE_TEXT.cityDetail.backButton}
      </button>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Column */}
        {/* Mobile: `contents` flattens this wrapper so each card becomes a
            direct grid item of the outer grid and its individual `order-*`
            class controls its mobile slot. Desktop: `lg:block` restores the
            wrapper as the left column. */}
        <div className="contents lg:block lg:col-span-4 lg:space-y-8">
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="order-1 relative group rounded-[3rem] overflow-hidden aspect-[4/5] lg:aspect-[1/1] shadow-2xl shadow-slate-300"
          >
            <img src={city.heroImage} className="absolute inset-0 w-full h-full object-cover transition-transform duration-700" alt={city.name} />
            <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-900/40 to-transparent"></div>
            <div className="absolute inset-0 p-8 flex flex-col justify-end">
              <div className="text-white/5 text-[10rem] font-black tracking-tighter absolute top-0 right-0 pointer-events-none select-none uppercase -mt-20 -mr-10">{city.name.toUpperCase()}</div>
              <div className="bg-orange-400 text-slate-950 text-[10px] font-black uppercase tracking-[0.2em] px-4 py-1.5 rounded-full w-fit mb-6 shadow-lg">{t.verifiedBadge}</div>
              <h1 className="text-5xl lg:text-7xl text-white font-black mb-4 leading-tight tracking-tight uppercase">{t.oneDayInPrefix}<br/>{t.oneDayInLink} {city.name}</h1>
              <div className="bg-brand text-slate-950 text-xs font-bold px-6 py-3 rounded-2xl flex items-center gap-3 w-fit shadow-xl uppercase tracking-widest">
                <Check size={18} className="text-slate-950" strokeWidth={3} />
                {city.verdict}
              </div>
            </div>
          </motion.div>

          <div className="order-4 bg-white rounded-[2.5rem] p-8 shadow-sm border border-slate-100">
            <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-400 mb-8 border-b border-slate-50 pb-4">{t.gettingThere}</h4>
            <div className="space-y-4">
              {city.reach.map((r, i) => (
                <div key={i} className="flex items-center gap-6 group hover:translate-x-2 transition-transform">
                  <div className="w-12 h-12 rounded-2xl bg-slate-50 flex items-center justify-center text-slate-400 group-hover:bg-brand group-hover:text-slate-950 transition-all shadow-sm">
                    {r.type === 'Train' ? <Train size={20} /> : r.type === 'Road' ? <Car size={20} /> : r.type === 'Flight' ? <Plane size={20} /> : <Bus size={20} />}
                  </div>
                  <div className="flex-1">
                    <div className="flex justify-between items-center">
                      <h5 className="text-[13px] font-black text-slate-800">{r.detail}</h5>
                      <span className="text-[10px] font-black text-brand">{r.cost}</span>
                    </div>
                    <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mt-0.5">{r.time} • {r.hub}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="order-5 bg-emerald-50/20 rounded-[2.5rem] p-8 border border-emerald-100">
            <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-emerald-600 mb-6 flex items-center gap-3">
              <AlertCircle size={16} />
              {t.survivalHeading}
            </h4>
            <div className="space-y-4">
              {city.tips.slice(0, 3).map((tip, i) => (
                <div key={i} className="flex gap-4 items-start">
                  <div className="w-2 h-2 bg-emerald-400 rounded-full mt-1.5 shrink-0"></div>
                  <p className="text-[13px] font-bold text-emerald-950 leading-relaxed italic opacity-80">{tip}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Middle Column */}
        {/* Middle column. The visual card styling was lifted into the inner
            div so the outer wrapper can be `contents` on mobile without
            losing its background or rounding. On desktop the wrapper stacks
            timeline + must-try with lg:space-y-8 so the middle column ends
            near the same baseline as Survival (left) and Budget (right). */}
        <div className="contents lg:block lg:col-span-5 lg:space-y-8">
          <div className="order-3 lg:order-none bg-white rounded-[3.5rem] shadow-xl shadow-slate-200/40 border border-slate-100 overflow-hidden relative">
          {/* Heading now sits above the quick-filter chips so "THE TIMELINE"
              stays on a single line even on narrower lg widths. Chips moved
              down into the row below — same buttons, same logic, just a
              cleaner vertical stack instead of a cramped split row. */}
          <div className="p-10 border-b border-slate-50 sticky top-0 bg-white/90 backdrop-blur-md z-40">
            <div className="flex items-baseline justify-between gap-4">
              <h3 className="text-xl font-black tracking-[0.2em] text-slate-900 uppercase whitespace-nowrap">{t.timelineTitle}</h3>
              <p className="text-brand text-[10px] font-black uppercase tracking-widest whitespace-nowrap">{t.timelineSub}</p>
            </div>
            <div className="flex gap-2 mt-4 flex-wrap">
              {t.quickFilters.map(tag => (
                <button key={tag} onClick={() => setActivePersonality(tag)} className={`px-4 py-2 text-[9px] font-black border border-slate-100 rounded-xl transition-all uppercase tracking-widest ${activePersonality === tag ? 'bg-slate-900 text-white border-slate-900' : 'bg-slate-50 text-slate-400 hover:text-brand'}`}>{tag}</button>
              ))}
            </div>
          </div>

          <div className="p-10 space-y-12 relative">
            <div className="absolute left-[59px] top-12 bottom-12 w-[1px] bg-slate-100"></div>
            <AnimatePresence mode="popLayout">
              {city.itinerary.map((item, i) => {
                const isMatch = activePersonality === 'All' || item.personalities.includes(activePersonality);
                return (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{
                      opacity: isMatch ? 1 : 0.1,
                      filter: isMatch ? 'blur(0px)' : 'blur(1px)'
                    }}
                    className="relative pl-16 flex flex-col"
                  >
                    <div className="absolute left-[-2px] top-0 w-12 h-12 bg-white flex items-center justify-center z-10">
                      <div className={`itinerary-dot ${isMatch ? 'bg-brand' : 'bg-slate-100 shadow-none grayscale'}`}></div>
                    </div>
                    <div className="mb-2">
                      <div className="flex items-center gap-4 text-[10px] font-black tracking-widest text-slate-400">
                        <span className={isMatch ? 'text-brand' : ''}>{item.time}</span>
                        <span className="w-6 h-[0.5px] bg-slate-100"></span>
                        <span>{item.duration}</span>
                      </div>
                    </div>
                    <h4 className={`text-xl font-black tracking-tight mb-2 ${isMatch ? 'text-slate-900' : 'text-slate-300'}`}>{item.place}</h4>
                    <p className={`text-[13px] font-medium leading-relaxed max-w-sm mb-4 ${isMatch ? 'text-slate-500' : 'text-slate-200'}`}>
                      {item.description}
                    </p>
                    {/* Show at most the 3 most relevant personality tags per
                        stop. If a quick-filter (activePersonality) matches
                        this stop, surface it first so it's always visible
                        even if it'd otherwise be past the cap. */}
                    <div className="flex flex-wrap gap-2">
                      {(() => {
                        const all = item.personalities;
                        const ranked = activePersonality !== 'All' && all.includes(activePersonality)
                          ? [activePersonality, ...all.filter(p => p !== activePersonality)]
                          : all;
                        return ranked.slice(0, 3).map(p => (
                          <span key={p} className={`text-[9px] font-black uppercase px-2 py-0.5 rounded-lg border transition-all ${isMatch && p === activePersonality ? 'bg-brand text-slate-950 border-brand' : 'bg-slate-50 text-slate-300 border-slate-100'}`}>{p}</span>
                        ));
                      })()}
                    </div>
                  </motion.div>
                );
              })}
            </AnimatePresence>
          </div>
          </div>

          {/* Must-Try Bites — now lives inside the middle column below the
              timeline, filling the previously-empty area between Survival
              (left) and Budget (right). Same per-item card design as before
              — only the dimensions/position changed per changes.docx. */}
          {city.mustTry.length > 0 && (
            <div className="order-9 lg:order-none">
              <h3 className="text-2xl font-black uppercase tracking-tight text-slate-900 mb-6 px-2">{t.mustTryTitle}</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {city.mustTry.map(item => (
                  <div key={item.name} className="bg-white rounded-[2rem] p-6 border border-slate-100 shadow-sm flex gap-4 items-start">
                    <div className="w-11 h-11 bg-brand/10 text-brand rounded-2xl flex items-center justify-center shrink-0">
                      <Utensils size={18} />
                    </div>
                    <div>
                      <h4 className="text-sm font-black uppercase tracking-tight text-slate-900 mb-1">{item.name}</h4>
                      <p className="text-[12px] text-slate-500 leading-relaxed">{item.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Right Column */}
        <div className="contents lg:block lg:col-span-3 lg:space-y-8">
          <div className="order-2 bg-white rounded-[2.5rem] px-6 py-8 shadow-sm border border-slate-100 text-center">
            <h4 className="text-[10px] font-black uppercase tracking-[0.4em] text-slate-400 mb-4">{t.mintScoreTitle}</h4>

            {/* Meter enlarged ~30% (230px → 300px) and card padding tightened
                (p-10 → px-6 py-8) so the gauge fills the card efficiently
                without ballooning the card's overall height. */}
            <div className="relative w-full max-w-[300px] mx-auto">
              {/*
                Semi-circular gauge. Geometry: centre (50,50), radius 40, so the
                arc spans (10,50)→(90,50) over the top. Arc length = π·40.
                The green progress is a dash of length (arc · score/10) starting
                from the LEFT end of the path, so it grows left→right with the
                score. Scoring logic is untouched — both the fill fraction and
                the needle angle derive from the same `city.rating`.
              */}
              <svg className="w-full h-auto block gauge-svg" viewBox="0 0 100 56">
                <path
                  d="M10 50 A40 40 0 0 1 90 50"
                  fill="none" stroke="#F1F5F9" strokeWidth="9" strokeLinecap="round"
                />
                <path
                  d="M10 50 A40 40 0 0 1 90 50"
                  fill="none" stroke="#00B894" strokeWidth="9" strokeLinecap="round"
                  strokeDasharray={`${(Math.PI * 40 * city.rating / 10).toFixed(2)} ${(Math.PI * 40).toFixed(2)}`}
                  style={{ transition: 'stroke-dasharray 1.2s ease-out' }}
                />
                {/* Long, slim needle matching the new.jpg reference: tip
                    extended to y=11 (radius 39, almost touching the inner
                    edge of the coloured band) and base widened slightly
                    (2 units half-width) so the shaft visibly tapers as it
                    exits the pivot cap. */}
                <motion.polygon
                  points="50,11 48,50 52,50"
                  fill="#0F172A"
                  initial={{ rotate: -90 }}
                  animate={{ rotate: -90 + (city.rating / 10 * 180) }}
                  transition={{ duration: 1.4, type: 'spring', bounce: 0.22 }}
                  style={{ originX: '50px', originY: '50px' }}
                />
                {/* Clock-hub pivot cap: solid black with a larger white
                    inner dot (r=2) per new.jpg — gives the meter a more
                    speedometer-like, mechanical feel. */}
                <circle cx="50" cy="50" r="5" fill="#0F172A" />
                <circle cx="50" cy="50" r="2" fill="#FFFFFF" />
              </svg>
              {/* Slightly lower and slightly smaller numeric score so the
                  pivot has visible breathing room above it. */}
              <div className="text-3xl font-black text-slate-950 tracking-tighter leading-none mt-2">
                {Math.round(city.rating * 10)}
              </div>
            </div>
            <p className="text-[9px] font-black uppercase tracking-widest text-slate-400 mt-4 leading-tight">{t.mintScoreFooter}</p>
          </div>

          <div className="order-7 bg-slate-950 rounded-[3rem] p-10 shadow-2xl shadow-slate-950/40 text-white overflow-hidden">
            <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-white/30 mb-8">{t.matrixTitle}</h4>
            <div className="space-y-10">
              <MatrixVisual label={t.effortLabel} value={combinedEffort} level={combinedEffort > 70 ? t.effortLevelHigh : t.effortLevelMid} color="bg-orange-500" />
              <MatrixVisual label={t.payoffLabel} value={city.matrix.payoff} level={t.payoffLevel} color="bg-indigo-500" />
            </div>
          </div>

          <div className="order-6 bg-white rounded-[2.5rem] shadow-sm border border-slate-100 overflow-hidden flex">
            <div className="flex-1 glass-green p-8 border-r border-slate-50">
              <span className="text-[8px] font-black uppercase tracking-widest text-emerald-600 bg-white/80 px-2 py-0.5 rounded-md border border-emerald-500/10 mb-6 inline-block">{t.prosLabel}</span>
              <div className="space-y-5 mt-4">
                {city.pros.map(p => (
                  <div key={p} className="flex gap-3 text-[10px] font-bold text-slate-800 leading-tight">
                    <Check size={12} className="text-emerald-500 shrink-0 mt-0.5" strokeWidth={3} />
                    {p}
                  </div>
                ))}
              </div>
            </div>
            <div className="flex-1 glass-red p-8">
              <span className="text-[8px] font-black uppercase tracking-widest text-rose-600 bg-white/80 px-2 py-0.5 rounded-md border border-rose-500/10 mb-6 inline-block">{t.consLabel}</span>
              <div className="space-y-5 mt-4">
                {city.cons.map(c => (
                  <div key={c} className="flex gap-3 text-[10px] font-bold text-slate-800 leading-tight">
                    <X size={12} className="text-rose-500 shrink-0 mt-0.5" strokeWidth={3} />
                    {c}
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Blueprint Budget — repositioned to the right column to mirror
              the Survival card on the left, filling the previously empty
              area opposite. Card visuals, values and INR data unchanged. */}
          <div className="order-8 bg-white rounded-[2.5rem] p-8 shadow-sm border border-slate-100">
            <div className="flex items-center gap-4 mb-6 border-b border-slate-50 pb-5">
              <div className="w-11 h-11 bg-slate-950 rounded-2xl flex items-center justify-center text-brand shrink-0">
                <Utensils size={18} />
              </div>
              <div>
                <h4 className="text-[13px] font-black tracking-tight uppercase text-slate-900">{t.budgetTitle}</h4>
                <p className="text-[9px] text-slate-400 font-bold uppercase tracking-[0.2em] mt-0.5">{t.budgetSubPrefix}{city.name}</p>
              </div>
            </div>
            <div className="space-y-3">
              <div className="flex items-center justify-between bg-slate-50 border border-slate-100 rounded-2xl px-5 py-3">
                <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{t.backpacker}</span>
                <span className="text-sm font-black text-slate-900">{city.budget.backpacker}</span>
              </div>
              <div className="flex items-center justify-between bg-brand rounded-2xl px-5 py-4 shadow-lg shadow-brand/20">
                <span className="text-[9px] font-black text-slate-950/70 uppercase tracking-widest">{t.optimum}</span>
                <span className="text-base font-black text-slate-950">{city.budget.recommended}</span>
              </div>
              <div className="flex items-center justify-between bg-slate-50 border border-slate-100 rounded-2xl px-5 py-3">
                <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{t.luxury}</span>
                <span className="text-sm font-black text-slate-900">{city.budget.luxury}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

    </motion.div>
  );
}

function LiteCityView({ city, onExploreVerified }: { city: LiteCity; onExploreVerified: () => void }) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="max-w-5xl mx-auto px-4 py-8"
    >
      <motion.div
        initial={{ y: 20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        className="relative rounded-[3rem] overflow-hidden shadow-2xl shadow-slate-300 aspect-[16/9] mb-8"
      >
        <img src={city.image} className="absolute inset-0 w-full h-full object-cover" alt={city.name} />
        <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-900/40 to-transparent"></div>
        <div className="absolute inset-0 p-8 md:p-12 flex flex-col justify-end">
          <div className="bg-brand text-slate-950 text-[10px] font-black uppercase tracking-[0.2em] px-4 py-1.5 rounded-full w-fit mb-4 shadow-lg">Quick Overview</div>
          <h1 className="text-5xl md:text-7xl text-white font-black mb-3 leading-tight tracking-tight uppercase">{city.name}</h1>
          <p className="text-white/80 text-base md:text-lg font-medium tracking-wide">{city.state} — {city.tagline}</p>
        </div>
      </motion.div>

      <div className="bg-brand/5 border border-brand/20 rounded-[2rem] p-6 mb-8 flex items-start gap-4">
        <AlertCircle size={20} className="text-brand shrink-0 mt-0.5" />
        <div>
          <h4 className="text-sm font-black uppercase tracking-tight text-brand mb-1">Full Blueprint In Production</h4>
          <p className="text-[13px] text-slate-600 leading-relaxed">
            A locally-verified 24-hour blueprint for {city.name} is being walked end-to-end by our reviewers. The overview below is drawn from community data while we finalize the full guide.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 bg-white rounded-[2.5rem] p-8 shadow-sm border border-slate-100">
          <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-400 mb-6 border-b border-slate-50 pb-4">Top Highlights</h4>
          <div className="space-y-4">
            {city.attractions.map((a, i) => (
              <div key={a} className="flex items-center gap-5 group">
                <div className="w-10 h-10 rounded-2xl bg-slate-50 flex items-center justify-center text-slate-500 group-hover:bg-brand group-hover:text-slate-950 transition-all font-black text-sm">
                  {String(i + 1).padStart(2, '0')}
                </div>
                <h5 className="text-[14px] font-black text-slate-800">{a}</h5>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-slate-950 rounded-[2.5rem] p-8 shadow-2xl shadow-slate-950/40 text-white">
          <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-white/30 mb-6">Best For</h4>
          <div className="flex flex-wrap gap-2">
            {city.bestFor.map(b => (
              <span key={b} className="bg-white/10 text-white px-3 py-1.5 rounded-xl text-[10px] font-black uppercase tracking-widest">{b}</span>
            ))}
          </div>
          <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-white/30 mt-8 mb-6">Personality Fit</h4>
          <div className="flex flex-wrap gap-2">
            {city.personalities.map(p => (
              <span key={p} className="bg-brand text-slate-950 px-3 py-1.5 rounded-xl text-[10px] font-black uppercase tracking-widest">{p}</span>
            ))}
          </div>
        </div>
      </div>

      <div className="mt-12 text-center">
        <button
          onClick={onExploreVerified}
          className="bg-slate-950 text-white px-8 py-4 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-brand hover:text-slate-950 transition-colors inline-flex items-center gap-3"
        >
          Browse Verified Blueprints <ArrowRight size={14} />
        </button>
      </div>
    </motion.div>
  );
}

// --- New Views ---

function PageHeader({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle?: string }) {
  return (
    <div className="max-w-7xl mx-auto px-4 pt-16 pb-10 text-center">
      <div className="bg-brand/10 border border-brand/20 text-brand text-[10px] font-black uppercase tracking-[0.3em] px-4 py-2 rounded-full w-fit mx-auto mb-6">
        {eyebrow}
      </div>
      <h1 className="text-4xl md:text-6xl font-black tracking-tighter uppercase text-slate-950 mb-4">{title}</h1>
      {subtitle && <p className="text-slate-500 text-base max-w-2xl mx-auto leading-relaxed">{subtitle}</p>}
    </div>
  );
}

function DestinationsView({ onCityClick }: { onCityClick: (id: string) => void }) {
  const t = SITE_TEXT.destinationsPage;
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader
        eyebrow={t.eyebrow}
        title={t.title}
        subtitle={t.subtitle(DESTINATION_LIST.length)}
      />
      <section className="max-w-7xl mx-auto px-4">
        <div className="city-grid">
          {DESTINATION_LIST.map(c => (
            <CityCard
              key={c.id}
              title={c.name}
              tagline={c.tagline}
              image={c.image}
              rating={c.rating}
              onClick={() => onCityClick(c.id)}
            />
          ))}
        </div>
      </section>
    </motion.div>
  );
}

function PersonaGuidesView({ onCityClick }: { onCityClick: (id: string) => void }) {
  const [selected, setSelected] = useState<string>('All');
  const matches = useMemo(() => destinationsForPersona(selected), [selected]);
  const t = SITE_TEXT.personasPage;
  const fb = SITE_TEXT.filterBar;

  // Pagination kept compatible with the homepage's 12-per-page grid.
  const [page, setPage] = useState(1);
  useEffect(() => { setPage(1); }, [selected]);
  const pageCount = Math.max(1, Math.ceil(matches.length / HOME_PAGE_SIZE));
  const safePage = Math.min(page, pageCount);
  const visible = matches.slice((safePage - 1) * HOME_PAGE_SIZE, safePage * HOME_PAGE_SIZE);

  const gridRef = useRef<HTMLDivElement>(null);
  const goToPage = (p: number) => {
    setPage(p);
    gridRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader
        eyebrow={t.eyebrow}
        title={t.title}
        subtitle={t.subtitle}
      />
      <section className="max-w-7xl mx-auto px-4">
        {/* Personality-only filter — same chips and shell as the homepage
            filter bar, for a unified discovery experience. */}
        <div className="bg-white rounded-[2.5rem] p-6 md:p-8 shadow-xl shadow-slate-200/40 mb-12 border border-slate-100/50">
          <div className="flex items-center justify-between gap-4 pb-4 border-b border-slate-50">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 bg-slate-950 rounded-xl flex items-center justify-center text-brand shrink-0">
                <SlidersHorizontal size={16} />
              </div>
              <span className="text-[11px] font-black uppercase tracking-widest text-slate-900">
                {fb.results(matches.length)}
              </span>
            </div>
            {selected !== 'All' && (
              <button
                type="button"
                onClick={() => setSelected('All')}
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest text-rose-500 bg-rose-50 hover:bg-rose-100 transition-colors"
              >
                <RotateCcw size={13} /> {fb.clearFilters}
              </button>
            )}
          </div>
          <div className="flex items-start gap-4 pt-4">
            <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 w-24 shrink-0 pt-2.5 hidden md:block">{fb.personalityLabel}</span>
            <div className="flex gap-2 overflow-x-auto no-scrollbar flex-1 py-0.5">
              {PERSONALITIES.map(p => (
                <FilterChip key={p.id} active={selected === p.id} onClick={() => setSelected(p.id)}>
                  {p.icon}{p.id}
                </FilterChip>
              ))}
            </div>
          </div>
        </div>

        <div ref={gridRef} className="city-grid">
          {visible.map(c => (
            <CityCard
              key={c.id}
              title={c.name}
              tagline={c.tagline}
              image={c.image}
              rating={c.rating}
              onClick={() => onCityClick(c.id)}
            />
          ))}
        </div>
        {matches.length === 0 && (
          <div className="text-center py-20 text-slate-400 text-sm font-bold uppercase tracking-widest">
            {SITE_TEXT.emptyStates.personaPageNoMatch(selected)}
          </div>
        )}

        {pageCount > 1 && (
          <Pagination page={safePage} pageCount={pageCount} onChange={goToPage} />
        )}
      </section>
    </motion.div>
  );
}

function AboutView({ onExploreClick }: { onExploreClick: () => void }) {
  const t = SITE_TEXT.aboutPage;
  const stats = t.stats.map(s =>
    s.value === 'auto-cities-count' ? { ...s, value: DESTINATION_LIST.length.toString() } : s
  );

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader
        eyebrow={t.eyebrow}
        title={t.title}
        subtitle={t.subtitle}
      />
      <section className="max-w-5xl mx-auto px-4">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-16">
          {stats.map(s => (
            <div key={s.label} className="bg-white rounded-[2rem] p-6 border border-slate-100 shadow-sm text-center">
              <div className="text-3xl font-black text-slate-950 tracking-tighter mb-2">{s.value}</div>
              <div className="text-[9px] font-black uppercase tracking-widest text-slate-400">{s.label}</div>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
          {ABOUT_PILLARS.map(p => (
            <div key={p.title} className="bg-white rounded-[2.5rem] p-8 border border-slate-100 shadow-sm">
              <div className="w-12 h-12 bg-brand/10 text-brand rounded-2xl flex items-center justify-center mb-6">
                {p.icon}
              </div>
              <h3 className="text-lg font-black uppercase tracking-tight text-slate-900 mb-3">{p.title}</h3>
              <p className="text-[13px] text-slate-500 leading-relaxed">{p.body}</p>
            </div>
          ))}
        </div>

        <div className="bg-slate-950 rounded-[3rem] p-12 text-white text-center">
          <h2 className="text-3xl md:text-4xl font-black tracking-tighter uppercase mb-4">{t.ctaTitle}</h2>
          <p className="text-slate-400 max-w-xl mx-auto mb-8 leading-relaxed">{t.ctaBody}</p>
          <button
            onClick={onExploreClick}
            className="bg-brand text-slate-950 px-8 py-4 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-white transition-colors"
          >
            {t.ctaButton}
          </button>
        </div>
      </section>
    </motion.div>
  );
}

function SearchView({ initialQuery, onCityClick, onSubmitSearch }: { initialQuery: string; onCityClick: (id: string) => void; onSubmitSearch: (q: string) => void }) {
  const [query, setQuery] = useState(initialQuery);
  useEffect(() => { setQuery(initialQuery); }, [initialQuery]);
  const t = SITE_TEXT.searchPage;

  const results = useMemo(() => searchDestinations(query), [query]);

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader
        eyebrow={t.eyebrow}
        title={query ? `"${query}"` : t.fallbackTitle}
        subtitle={t.summary(results.length)}
      />
      <section className="max-w-7xl mx-auto px-4">
        <div className="relative max-w-2xl mx-auto mb-12 group">
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => { if (e.key === 'Enter') onSubmitSearch(query); }}
            placeholder={t.refinePlaceholder}
            className="w-full h-14 bg-white border border-slate-200 rounded-2xl pl-14 pr-6 text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-4 focus:ring-brand/20 focus:border-brand transition-all shadow-sm"
            autoFocus
          />
          <Search className="absolute left-5 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
        </div>
        {results.length > 0 ? (
          <div className="city-grid">
            {results.map(c => (
              <CityCard
                key={c.id}
                title={c.name}
                tagline={c.tagline}
                image={c.image}
                rating={c.rating}
                onClick={() => onCityClick(c.id)}
              />
            ))}
          </div>
        ) : (
          <div className="text-center py-20">
            <p className="text-slate-400 text-sm font-bold uppercase tracking-widest mb-4">{SITE_TEXT.emptyStates.searchNoMatchHeadline(query)}</p>
            <p className="text-slate-500 text-xs">{SITE_TEXT.emptyStates.searchHelp}</p>
          </div>
        )}
      </section>
    </motion.div>
  );
}

function InfoPageView({ topic, onHome }: { topic: InfoTopic; onHome: () => void }) {
  const content = INFO_CONTENT[topic];
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pb-20">
      <PageHeader eyebrow={SITE_TEXT.infoPage.eyebrow} title={content.title} subtitle={content.intro} />
      <section className="max-w-3xl mx-auto px-4">
        <div className="space-y-6">
          {content.sections.map(s => (
            <div key={s.heading} className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-sm">
              <h3 className="text-base font-black uppercase tracking-tight text-slate-900 mb-3">{s.heading}</h3>
              <p className="text-[14px] text-slate-600 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
        <div className="mt-12 text-center">
          <button
            onClick={onHome}
            className="bg-slate-950 text-white px-8 py-4 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-brand hover:text-slate-950 transition-colors inline-flex items-center gap-3"
          >
            {SITE_TEXT.infoPage.backHomeButton} <ArrowRight size={14} />
          </button>
        </div>
      </section>
    </motion.div>
  );
}

function MatrixVisual({ label, value, level, color }: any) {
  return (
    <div className="space-y-3">
      <div className="flex justify-between items-end">
        <span className="text-[10px] font-bold uppercase tracking-tighter text-white/90">{label}</span>
        <span className={`text-[10px] font-bold ${level === 'HIGH' || level === 'EXTREME' ? 'text-orange-400' : 'text-brand'}`}>{level}</span>
      </div>
      <div className="h-1.5 w-full bg-white/10 rounded-full overflow-hidden">
        <motion.div
          initial={{ width: 0 }}
          animate={{ width: `${value}%` }}
          className={`h-full ${color}`}
        />
      </div>
    </div>
  );
}

// --- Sub-Components ---

function CityCard({ title, tagline, image, rating, onClick }: any) {
  return (
    <motion.div
      whileHover={{ y: -10 }}
      className="group bg-white rounded-[2.5rem] overflow-hidden shadow-xl shadow-slate-200/50 cursor-pointer border border-transparent hover:border-brand/20 transition-all flex flex-col items-center text-center p-2"
      onClick={onClick}
    >
      <div className="w-full aspect-[4/3] relative overflow-hidden rounded-[2rem]">
        <img
          src={image}
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
          alt={title}
        />
        <div className="absolute top-4 right-4 bg-slate-900/90 backdrop-blur px-3 py-1.5 rounded-full font-black text-[10px] text-brand flex items-center gap-1.5 shadow-lg">
          <TrendingUp size={12} />
          {rating}
        </div>
      </div>
      <div className="p-6 w-full">
        <h3 className="text-xl font-black mb-1 text-slate-950 uppercase tracking-tight">{title}</h3>
        <p className="text-slate-400 text-[10px] font-bold uppercase tracking-[0.2em] mb-4">{tagline}</p>
        <div className="flex items-center justify-end border-t border-slate-50 pt-4">
          <span className="text-slate-950 font-black text-[10px] flex items-center gap-2 uppercase tracking-widest group-hover:text-brand transition-colors">
            {SITE_TEXT.cityCard.blueprintCta} <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
          </span>
        </div>
      </div>
    </motion.div>
  );
}
